from textblob.classifiers import NaiveBayesClassifier
from textblob import TextBlob

test = [
    ("youtubenaked and sexy woman with a tiny bikini #asian av sex https://t.co/BFlcTzLv3T", 'pos'),
    ("#granny anal vid taco bell group sex https://t.co/l6Zb14UYyo", 'pos'),
    ("#salma hayek pussy pics sex tv wwwnewportalin https://t.co/y1D4dWKAGx", 'pos'),
    ("#nude girl walk pics mallu sex video https://t.co/BXFdsuhXnX", 'pos'),
    ("#married women sex pics sex fantasies ideas https://t.co/nguJPbQMP5", 'pos'),
    ("#hentai cam camgirl college masturbation #big #teen #step #masturbating milf webcam massage #sexy masturbate... https://t.co/NilC9KX6zF", 'pos'),
    ("#bangladesi smart girl boobs and fuck video sex and grinding https://t.co/tPzA5OPkR3", 'pos'),
    ("#tied up black girl haveing sex with black brasileiro porno https://t.co/m5r0IoYnNN", 'pos'),
    ("#wtf #automotive porn #ultimate upskirtnation #portland #spy alexandria https://t.co/DcGZRDqa2Y", 'pos'),
    ("hot girls having sex free videos #naked pictures tara reid https://t.co/WvL75Ad0Nu", 'pos'),
    ("extreme sex free videos https://t.co/bX4p6CCCzb", 'pos'),
    ("#fucking girls vedios college amateur sex videos https://t.co/rpcpXxROz3", 'pos'),
    ("#girlssex and hotguy i like tight pussy https://t.co/RaKlhDVXbI", 'pos'),
    ("New video Five cock gangbang for ... has been published https://t.co/KdZQlniTan - #porn #porno #sex #smut #erotica #gifs #hotwife #MILF", 'pos'),
    ("#adult hannah montana what does it take to be a porn star https://t.co/QflNp1fj6S", 'pos'),
    ("This will make you horny https://t.co/qHL5CfUyRk #sex #nsfw #porn #naked #xxx #adult https://t.co/wJSa48D6fY", 'pos'),
    ("The Worst Video Game Sex Scenes https://t.co/51hLn0ahiS https://t.co/6JWZCfaWy5", 'pos'),
    ("this ting go with sense https://t.co/o9A6wZxUBJ", 'pos'),
    ("nude girl screensavers for mac #wolve sex https://t.co/lJqH9PGBsD", 'pos'),
    ("#watch free granny sex nude booty shaking videos https://t.co/MwgziblSXZ", 'pos'),
    ("vietnamese hotty cumming with toys and dick https://t.co/G4DCuSCNVg", 'pos'),
    ("#amateur porn thumbs hairy pussy galleries free https://t.co/ClJA0jdsTz", 'pos'),
    ("#sexy girls from sweden sex videos naked girls pillow fight https://t.co/ZyVNU35rBL", 'pos'),
    ("#hottest #incest #mom #milf #taboo #family #NSFW - Hottest incest action at realincest . info https://t.co/BOyrQYMCBY", 'pos'),
    ("lol how is it every conspiracy on the left that /pol/  'uncovers' has to do with children and sex traffickingnnthis... https://t.co/v0AfHMRhNz", 'pos'),
    ("love sex magig https://t.co/2nw3mSkkaB", 'pos'),
    ("#free old man porn tube indiansexy girl video https://t.co/zkZRCwfnub", 'pos'),
    ("#double anal pluged older men younger women sex video https://t.co/fq8tW2aulu", 'pos'),
    ("#easy way to have sex jamaican booty sex https://t.co/DORRDmETi9", 'pos'),
    ("I had a pussy-eating dream, it was nice", 'pos'),
    ("#lauren watts nude cafe sex in india https://t.co/c76GQ74Hcv", 'pos'),
    ("Migrant from Iraq forces 10-year-old girl to watch porn before raping her in Swedennhttps://t.co/y6xjtwLnYH https://t.co/NVzqIC7230", 'pos'),
    ("porn movies on net https://t.co/nuYfvJ5LWY", 'pos'),
    ("free asian porn sites https://t.co/CKL7lXOyIc", 'pos'),
    ("#fuck my ass porn older women fucking video https://t.co/UUIYt4UZ4I", 'pos'),
    ("#phone sex threesome rihanna new nude photos https://t.co/lg60MzaO2I", 'pos'),
    ("#nude teen stocking knockout porn https://t.co/ESxCMGIXGQ", 'pos'),
    ("porn actresses videos https://t.co/Ld6sT8Ikpd", 'pos'),
    ("#teacher sex movies really hot greek girls naked pic https://t.co/Uwqk26OASU", 'pos'),
    ("#5 guys and 1 girl sex video anna nicole smith nude gallery https://t.co/qtMUEzif7R", 'pos'),
    ("#videosof woman having sex doctor fetish porn https://t.co/J3ukBShuXQ", 'pos'),
    ("#hairy anus porn bear gryls naked https://t.co/uzZ8U3I8xM", 'pos'),
    ("Ethan suck my dick https://t.co/72upIi9dDJ", 'pos'),
    ("#nude photos of chyna wwwpunjabi sex naked girlsphotoscom https://t.co/nwSh2Kgi67", 'pos'),
    ("#porn galleries only tila anal https://t.co/zCVF88rXj6", 'pos'),
    ("#porn hardcore movies young emo blowjob https://t.co/1wVpEDtYkI", 'pos'),
    ("New video Asian babe Priva fucked hard has been published https://t.co/DeGgEClbwE - #porn #porno #sex #smut #erotica #gifs #hotwife #MILF", 'pos'),
    ("I agree https://t.co/kdB0X0fD9D", 'pos'),
    ("#anal bdsm stories ver shy school girls porn https://t.co/rASP3aOR5m", 'pos'),
    ("@Cosmopolitan If your partner has any skill at sex you don't need lube. why would you allow yourself to be penetrat... https://t.co/0RyNWNulix", 'pos'),
    ("porn tgp search #analgaysex https://t.co/n28v2UxYlg", 'pos'),
    ("#big cocks fucking wet pussy free online porn chat rooms https://t.co/00uinljywD", 'pos'),
    ("#oral sex toys for women naket girl porno https://t.co/luQA9e6sbk", 'pos'),
    ("#barbie hsu sex pussy pictures free https://t.co/p0aafyuEPL", 'pos'),
    ("#sex intercourse movies naked girl sexy short skirts girls https://t.co/SakuTn9dNQ", 'pos'),
    ("It could also be compared to society where sharia law is a reality right now. https://t.co/9v92rzoDn0", 'pos'),
    ("#history of sex cinema alabama married women looking for sex https://t.co/4X03amY1GI", 'pos'),
    ("a girl i know naked brothers band #videos of drunk girls having sex https://t.co/5YpJ4eiMjS", 'pos'),
    ("school girls porn pics https://t.co/HwvUSzeIhl", 'pos'),
    ("#black with white sex video sex bbw https://t.co/BLtutnvrRJ", 'pos'),
    ("#old lady lesbian sex japanese women sex video https://t.co/wH9ezcolAq", 'pos'),
    ("@antoniodematas She's in school paying for tuition doing porn in the valley", 'pos'),
    ("could the invention of porn be the culprit for the #whitegenocide", 'pos'),
    ("#white women big booty fuking best free online porn sites https://t.co/8pf7nWUWzK", 'pos'),
    ("sex toys store https://t.co/sIJ8Wymkw5", 'pos'),
    ("#petite amateur girls free porn rep sexi vedyo clip https://t.co/NZTzovQBtf", 'pos'),
    ("what do sex braclets mean https://t.co/zw7Ug5RCkn", 'pos'),
    ("#naked women and girls dancing bodystocking anal porn https://t.co/rIU8ChN6zn", 'pos'),
    ("Do you suck dick?  Why do you care?  https://t.co/K6CSZDh3i7", 'pos'),
    ("@Samuel_Turner1 pussy", 'pos'),
    ("Heaven * https://t.co/iPAZGmtf6F", 'pos'),
    ("nude women in actiion #free teen movies galleries sex https://t.co/K2shc2Neq2", 'pos'),
    ("#pretty blondes nude adult jokes sex https://t.co/vGYBCB1ZH5", 'pos'),
    ("#rumspringa porn blode pussy hair https://t.co/hZwFqprUAI", 'pos'),
    ("black bikini sex lady https://t.co/h9BO2wc1GB", 'pos'),
    ("sandy summers anal video #the best porn web https://t.co/0rpo0GLxeE", 'pos'),
    ("#teen flashing porn indonesian naked body https://t.co/YjYnQV1Rq4", 'pos'),
    ("#hot spanking sex guys fucking https://t.co/y7QXd1ai2J", 'pos'),
    ("pussy pump videos free https://t.co/NF0QnEW4Q1", 'pos'),
    ("He did what  he ate yo booty? https://t.co/U32mPCFoeM", 'pos'),
    ("#vivi hardcore girls laying porn caver paints https://t.co/zQGeco14DV", 'pos'),
    ("punk porn lady #nude huge boobs https://t.co/rZUJJs0AKX", 'pos'),
    ("#oral sex and diseases submitted sex tube https://t.co/lInqxhWAv7", 'pos'),
    ("avatar the last airbender cartoon sex https://t.co/MSB7tE6Qpg", 'pos'),
    ("@wudasupreme it's a female's job to do too much. Niggas just be out here, community dick and all, having the nerv... https://t.co/AyqSXVco21", 'pos'),
    ("@jiminpawk Well i can't relate bc I'm the type of 'same dick forever'  i won't share my mouth. One or nothing", 'pos'),
    ("#asia carrera anal scene real cheating sex stories https://t.co/HEdaJqOt8s", 'pos'),
    ("#teens fuckd hard porn images i want you sex scene https://t.co/z7GU998Mry", 'pos'),
    ("fat chick blowjob https://t.co/iuWg1Scmyj", 'pos'),
    ("#milf #pornography  -; https://t.co/3sl2oc70si &lt;-- Cuck Husband gives wife to 4 BBCs for gangbang https://t.co/SKbHd04HaU", 'pos'),
    ("#sexy ass porn movies big squirters https://t.co/VTLYXcWx1w", 'pos'),
    ("#nude australian beauties sex with old woman video https://t.co/PQQpKaELAF", 'pos'),
    ("#maureen larrazabal sex scene porn tube amateur https://t.co/SfUfVBvowM", 'pos'),
    ("17 Sex Ed Teachers Share The Dumbest Questions They've Heard https://t.co/8VyJviMpdR", 'pos'),
    ("#pussy poppin on a girls fucking monster cocks https://t.co/xd6SIkjHr0", 'pos'),
    ("I'm gonna have to give this a RT. I have done much more than fucked on that poor couch. https://t.co/BsyM67M2Bd", 'pos'),
    ("#khmer girl sex hotel girlfriend will not have sex https://t.co/YfoZD9Z3G6", 'pos'),
    ("I heard you eat pussy too, and I'm feelin that.", 'pos'),
    ("#free scavenger hunt ideas for adults katherine heigl sex scenes https://t.co/mDku5zui4p", 'pos'),
    ("sunny leone get fucked vived #free simpsons sex toons https://t.co/wmh8VWdMTI", 'pos'),
    ("Small Cock Man Teased and Abused in Locker Room! - Part 4 -... https://t.co/Z5DvRa91y0 #HANDJOBS via @clips4sale https://t.co/QaQ7jyTP28", 'pos'),
    ("Sunny Leone Revealed A Shocking Story About Her Sex Life https://t.co/XNSuA34UxX @newstracklive https://t.co/ckWpigN8Vr", 'pos'),
    ("&gt; 69 sex tricks women allways LOVE https://t.co/NoXpexF0eO", 'pos'),
    ("Mommy need dick. My pussy is hot! Im here; https://t.co/VBL2Khvu1R. https://t.co/SDhQ7qq7MW", 'pos'),
    ("anal sex in a car https://t.co/2UPRjxXnce", 'pos'),
    ("porn no download https://t.co/2u1yyV8yS1", 'pos'),
    ("nina hartleys guide to anal sex #art erotic sex https://t.co/y2jLiQhwyS", 'pos'),
    ("nds porn game #mary anne pornstar https://t.co/kOsxhvD7bj", 'pos'),
    ("#fucking daughter sex station tv https://t.co/cvdycflrad", 'pos'),
    ("barely teen sex clips #riki lake naked https://t.co/292HIa2wtK", 'pos'),
    ("bolivian teen pics #aletta ocean porn star https://t.co/C1B7LmD0up", 'pos'),
    ("Watch young boys gay sex fuck videos free Moaning and squeal https://t.co/C103VBwzGU", 'pos'),
    ("&gt; 69 sex tricks women allways LOVE https://t.co/ayvauS1g6u", 'pos'),
    ("#facial recognition porn wwwamericangirlporngirlscom https://t.co/kOBAz6KIYX", 'pos'),
    ("#pornstar gym 101 sex positions book https://t.co/WP96HPtnvG", 'pos'),
    ("#xxx free girls live sex hu https://t.co/exfsn7TmHy", 'pos'),
    ("#ali landry porn cought haveing sex https://t.co/0tIWn1SF94", 'pos'),
    ("Retweeted Sex NotesTM (@RealSexNotes):  When you\'re in a relationship , you should be proud to say 'thats my baby'.", 'pos'),
    ("#worlds fat porn boy girl jayden james sex movies https://t.co/omKwh9oBwZ", 'pos'),
    ("Site of girls who probably know &gt; https://t.co/ejYSDaJYKF #Sex #Luxembourg #Norway #Denmark https://t.co/FKBMxNgr69", 'pos'),
    ("#free powerpuff girls porn porn and india https://t.co/1RH8CPXrfn", 'pos'),
    ("#very thin naked women free video sex naughty girls https://t.co/lg60MzaO2I", 'pos'),
    ("#adult #sextoys #sex Strapless #StrapOn #dildos 55.00 https://t.co/DOc3bXVhAH https://t.co/lYjJSLqCiv", 'pos'),
    ("#Gay gay-porn-now: (via gay porn) https://t.co/fM1i2iMBy4 https://t.co/8EAqHhjOl0", 'pos'),
    ("&gt; 69 sex tricks women allways LOVE https://t.co/3V8psPkHvF", 'pos'),
    ("#girl naked outside/anime teen sex in republic dominican https://t.co/TkY3oB2PL2", 'pos'),
    ("#adult teaches teen porn www naked nature girls com https://t.co/ZVPOQG5ZL9", 'pos'),
    ("ebony ass sex #vintage ass fucking https://t.co/Xh3Yz1DtWq", 'pos'),
    ("#brutal tube porn big panties porn https://t.co/P57GjKnuNN", 'pos'),
    ("Hot mexican gay porn movietures and teen boy anal sex indulg https://t.co/xCJlOltiX8", 'pos'),
    ("amateur dildo porn https://t.co/3rkTA8xIN3", 'pos'),
    ("#uncircumcised #brussels banginghotmilf #naughty nudegirls #pussy wild  =&gt; https://t.co/AuYFmZq1Vp https://t.co/9rHQIMeRLS", 'pos'),
    ("#pussyorgasm #dick boobs virgin #only park https://t.co/2y7ph1niA5", 'pos'),
    ("#danger from i love ray j naked girls naked hypnose sex https://t.co/JUYpxR5pTJ", 'pos'),
    ("I'm such a pussy when it comes to me telling someone I like them fukkk haha", 'pos'),
    ("girl nude vietnam sex https://t.co/ew4l3WZ3Q5", 'pos'),
    ("Lusty fluffy pussy is waiting! Ram with your dick for wild nights! Check it yourself! https://t.co/FOWV8GutR1 https://t.co/oZpDKInPbU", 'pos'),
    ("@thevirdas first try to understand stand concept of arranged marriage. Age 20's mind is full of sex no love. https://t.co/TDcHLlTvMn", 'pos'),
    ("#wild home sex videos teensexfreedownloadvideo https://t.co/ODXWdKDJL6", 'pos'),
    ("#fun #sloppy clips4sale #bigjugs colchester #dick #letstalksex seafood https://t.co/CEizMvTS8u", 'pos'),
    ("#teacher sex hot sexiest women in 2007 https://t.co/B7HkGVju5P", 'pos'),
    ("#porno hub xxx best teen sex pics https://t.co/04wH6LAWMI", 'pos'),
    ("Free Lifetime Access! - https://t.co/zWRwwRdcfE #Sex #Porn https://t.co/ha7pI2lKt0", 'pos'),
    ("Wife got bitchy? Unlimited #sex #play!. Plunge into the ocean of pleasure!! - https://t.co/RPcXWxjbQS https://t.co/yMaca3hgKJ", 'pos'),
    ("#Porn #Sex #Amateur: Young Sex... https://t.co/GgSSUaCsy2 #foursome #groupsex #small-tits #teens", 'pos'),
    ("Chubby Wife Sucks Dick and Swallows Cum in the Bathroom! -... https://t.co/5acxgHfGwv #BLOWJOBS via @clips4sale https://t.co/0pESFyWdb4", 'pos'),
    ("Free uncircumcised gay male masturbation porn and boys tubes https://t.co/mwR9FzcTBD", 'pos'),
    ("#smoke pussy anal free picture https://t.co/Ri92aP8nXk", 'pos'),
    ("#school grils sexy anal milf sexy pictures https://t.co/O1Msy2zRDo", 'pos'),
    ("#solo girl striper video pink pussy sluts https://t.co/fHNFatXTO6", 'pos'),
    ("#summer house sex party latinas anal videos https://t.co/69v4CoDYHc", 'pos'),
    ("she is my idol https://t.co/5GCszaBEud", 'pos'),
    ("#Gay gay-porn-now: (via gay porn) https://t.co/I6IoATnAof https://t.co/skOpsqw9Ux", 'pos'),
    ("#edecanes porno chubbyland porn https://t.co/7xFNQEyoal", 'pos'),
    ("Slim blonde teen charmer Amelia gives oral sex and gets sexy ass fucked by a giant cock https://t.co/m5hUufbI5F https://t.co/ss0fcFr07X", 'pos'),
    ("I literally thought having sex was being in a relationship bruh like ", 'pos'),
    ("#adult video previews donkey female sex videos https://t.co/JBiUx0NSDG", 'pos'),
    ("woah... https://t.co/QN1EjNkLK0", 'pos'),
    ("#porno mistake the cone sex https://t.co/bi6GpbZFNR", 'pos'),
    ("@thickjuliet Would be perfect if i had sum pussy", 'pos'),
    ("#squirt in panties video phat ass ebony porn https://t.co/AXLm1AAR28", 'pos'),
    ("#hair sex gallery nude irish girls https://t.co/sY0XQnSpsh", 'pos'),
    ("#beach volleyball college girl fucked drunk girl anal sex https://t.co/DFe9JXCTBK", 'pos'),
    ("#do pornstars fake orgasms big tits porn site https://t.co/MrRc3wgOtS", 'pos'),
    ("@OfficiallyRichh Rich You Look Like If Harambe Had Sex With Kevin Hart", 'pos'),
    ("#sex firemen brittney skye sex video https://t.co/IIm0iL4kkC", 'pos'),
    ("high porn tube https://t.co/otbRTbdUNW", 'pos'),
    ("#xxx nude softball stocking tube porn https://t.co/LT25GGjSoR", 'pos'),
    ("@genjispussy im the opposite i have jerked off while hoxton is on my bed 1 foot away i just don't care. he's 4 year... https://t.co/NVynzzk18l", 'pos'),
    ("#old young lesbian porn surprise parties for adults https://t.co/Wcf55ArowF", 'pos'),
    ("My pussy is out of control! Help me! Im here ; https://t.co/vElhMgrMPM. https://t.co/g1glK1I0BT", 'pos'),
    ("malayalam anal sex story #mtv real world nude girls https://t.co/2hrol4VoLM", 'pos'),
    ("place dick ", 'pos'),
    ("The Worst Video Game Sex Scenes https://t.co/eYrcO3vyek https://t.co/dD3Wm3OqIb", 'pos'),
    ("#Hot #girls looking for wild #sex - https://t.co/ULnIDWtSbQ https://t.co/CFzCtEiEpY", 'pos'),
    ("#adult mega stores porn women pussy https://t.co/66feuDjNcT", 'pos'),
    ("I've watched this and its p good! I recommend it. https://t.co/gLbTtA8Hzt", 'pos'),
    ("Wet #SEX with #Hot Dubai Girls ,,, Online ,,, On your DM inbox ! Ask me for Prices April 27, 2017 at 06:45AM", 'pos'),
    ("#female sex freaks marie mcray anal https://t.co/WjPmFnbYLI", 'pos'),
    ("#porn scenes videos caribbean bikini girls sex https://t.co/YV6SzfFkaN", 'pos'),
    ("lovers pussy https://t.co/787XAjglvk", 'pos'),
    ("hobo sex pictures #free grannies sex https://t.co/DgXWCrfQkP", 'pos'),
    ("#doctor sex exam nude teen hardcore gallery https://t.co/nTufeGCi4K", 'pos'),
    ("#pretty black pornstars porn from trinidad https://t.co/nT844mx9kN", 'pos'),
    ("#1000 porn pictures keez porno https://t.co/hfi0lBTDCT", 'pos'),
    ("#sex ass cum mother daughter porn https://t.co/ZU0zqpKn0o", 'pos'),
    ("#vanilla pussy free hard gongolese video https://t.co/Sy2CaXx2sD", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/w3ipU64uqR", 'pos'),
    ("#mateur porn tube mms clips sex https://t.co/ul68aWw5Gc", 'pos'),
    ("#Gay faptogayporn: Best Gay Porn Sites - faptogayporn | Tumblr -... https://t.co/EThY9YpcXx https://t.co/AMpEPSlwqd", 'pos'),
    ("#101 sex positions book olderwomensexmovie https://t.co/K6KwPtHryp", 'pos'),
    ("#girls naked hypnose sex crash 1996 sex scenes https://t.co/B8ouCn39b7", 'pos'),
    ("Hi Baby! Smutty momy wet! Wanny play with my pussy now?  ; https://t.co/RhGCR8SI68. https://t.co/5NUlyGqlzn", 'pos'),
    ("Porn is lame", 'pos'),
    ("meet women for sex lakefield minnesota #free sweet pussy https://t.co/MWHW1c4WjC", 'pos'),
    ("#dildo bike sex games on pc https://t.co/EYC3jQIKbi", 'pos'),
    ("Slim and busty brunette slave Yvette Leigh gets tied up and pussy fucked with a dildo https://t.co/LiNoyVMTkU https://t.co/cmWLZBjKtm", 'pos'),
    ("free animated shemale porn #wet cuties https://t.co/zc3wctNLsk", 'pos'),
    ("Daily porn videos https://t.co/eAFNSo0pNi", 'pos'),
    ("Irresistible brunette babe Kyanne Lee smoking and sucking a giant cock with lust https://t.co/wpPMVgNqtP https://t.co/McAuI88eIM", 'pos'),
    ("adul sex games #nude feels good video https://t.co/TTlsvUDFEh", 'pos'),
    ("porn cry #blond xxx girls pics https://t.co/SI48OdTwrT", 'pos'),
    ("#constance marie nude picture zina porn https://t.co/qA9tnD3Wyl", 'pos'),
    ("#non nude jailbait how to have fake sex https://t.co/5t7yuOSR4N", 'pos'),
    ("#sexey girls and boys tenager sex magazine https://t.co/15sjDzE4XX", 'pos'),
    ("#peruanas amateurs got sex video https://t.co/F925NwblCT", 'pos'),
    ("#northern women fucking guys porno bat porn https://t.co/DHECD5plvS", 'pos'),
    ("Huge breasted blonde hoe gives oral sex and gets slick beaver fucked https://t.co/8vcLNJ6it5 https://t.co/jpPn8cxZGF", 'pos'),
    ("https://t.co/O2aJeK6Mr3: Asian screams when you eat pussy https://t.co/cgkjYG6OTS", 'pos'),
    ("@Hmmnya_0613 @BTS_twt Sign now and share! ARMYS please spread the petition so we can achieve 150k that's needed.  https://t.co/rr2S6qKx5p", 'pos'),
    ("#black leggings sex amateur vido https://t.co/qyDboF2dzT", 'pos'),
    ("naked girls from finland porn https://t.co/U5FUyWBCX6", 'pos'),
    (" he stupiddddd https://t.co/eKJ3tW7dHc", 'pos'),
    ("crank sex sceen https://t.co/YkTh9m046p", 'pos'),
    ("@xoxo__teejay Got that type of dick that make a white Girl say.", 'pos'),
    ("#gif animations adult betty blue sex scene video https://t.co/6djv9lXlyv", 'pos'),
    ("Choking during sex", 'pos'),
    ("#best ebony porn movie donkey fucking a girl free videos https://t.co/W2H9FY7B8I", 'pos'),
    ("Hi Baby! Wanna play with my pussy? mom waiting for you here.  ; https://t.co/wMcEoJEvLi. https://t.co/jAiOzOolz7", 'pos'),
    ("#period sex movie women's sexy tops https://t.co/Sr3fumolgQ", 'pos'),
    ("pictures pussy of rashel mc adams free prono #unshaved nude https://t.co/PKCMQetFfP", 'pos'),
    ("#pills that make women want to have sex black man hurt teenager sex video https://t.co/qIe1Q5nug0", 'pos'),
    ("mexican granny loves to engulf dick and plays with her dildo https://t.co/9QsPfWyrm7", 'pos'),
    ("Full Movie: https://t.co/rCScA8VPd4 Seductive blonde MILF Krissy Lynn uncovering her gorgeous curves https://t.co/EWHGBrQJtw", 'pos'),
    ("#swingers sex vids somali girls sex videos free https://t.co/q0ZGamEIcY", 'pos'),
    ("wet hairy black pussy https://t.co/uF4ESgD9IZ", 'pos'),
    ("some of yall put dick/men in general  on such a high pedestal there r better things in life relax lmao", 'pos'),
    ("#Gay More Best Gay Porn Sites or Gay Porn Pay Sites https://t.co/qTRJzds9ME https://t.co/kJ0feF4aYb", 'pos'),
    ("#naked dorm party 2 girls 1 guy free porn videos https://t.co/VZbSNqvntn", 'pos'),
    ("#jesse jane porn free world teen chubby model sexi videos https://t.co/IVojJ8G1Tc", 'pos'),
    ("#find sex in my area for free panty in anal https://t.co/diVYxCBpMt", 'pos'),
    ("icarly naked having sex in hd free https://t.co/UnakbbxOhd", 'pos'),
    ("#free video passed out ameture sex vids https://t.co/Vn8gB7W1nQ", 'pos'),
    ("Free Cam #Shows on Real #Sex #Webcams. Absolute privacy guaranteed - https://t.co/pijyybZtc9 https://t.co/VvJD0Asvqu", 'pos'),
    ("Tied bitch learns to swallow cum load. Free video https://t.co/qiwelUWcLU   #tiedbitch  #cumswallow  #cumload  #blowjob", 'pos'),
    ("Master of that pussy, sexual Yoda", 'pos'),
    ("Live sex show with adorable #ChiChi at #Chaturbate at this moment https://t.co/aVcsU2bR8n", 'pos'),
    ("Real Video The Teen Boys Having Gay Sex Cinema And Cute Emo Twinks - https://t.co/K7j3iDG9su - #porn #gay #gayvideos #gayporn #gayxxx", 'pos'),
    ("#place to fuck russian girls in mumbai shaking porn https://t.co/YM1THmOI2n", 'pos'),
    ("sex with sister movies #paris hilton sex vidoes https://t.co/2rscl21rEz", 'pos'),
    ("#teen babes sex videos shirt porn https://t.co/PrjHAyJgjA", 'pos'),
    ("@JaySn95 Jay Boostang Hi there My partner and i invite you to this specific porn cam cost-free register Click on my profile.", 'pos'),
    ("#porno costarica sex with my young sister https://t.co/zgTWDsuCjZ", 'pos'),
    ("Ultra sexy black hooker Audrey James showing massive big tits and sucking a giant cock https://t.co/1IrzWuB3TL https://t.co/Wmrx2bo1X3", 'pos'),
    ("#adult world adult madoona sex https://t.co/ORWjnAWX5k", 'pos'),
    ("mexican granny loves to engulf dick and plays with her dildo https://t.co/7FVb4X2n9m", 'pos'),
    ("#mai lin porn star free porn dad and daughter https://t.co/aipO5lEQCK", 'pos'),
    ("#my sisters nude free betty boop porn https://t.co/sARKoPIEVK", 'pos'),
    ("#Gay More Best Gay Porn Sites or Gay Porn Pay Sites https://t.co/zMbMgNcJ5c https://t.co/cZzvLUtnrr", 'pos'),
    ("I'm Finna take this advice https://t.co/KdB7Lacwd8", 'pos'),
    ("#lisa hannigan naked free adult porn amateur https://t.co/TqUDQNhKFQ", 'pos'),
    ("#shaved pussy xxx free simpson sex video https://t.co/fEaCeoS7RH", 'pos'),
    ("#solo mom pussy nude amateur women over 30 pictures https://t.co/8GsOPMsCtg", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/S7FrKHP5QV", 'pos'),
    ("#high definition porn streaming bangaldesh nude school girl sex movies https://t.co/ac2UcKf5ts", 'pos'),
    ("@HoneyGoldxx DAMN.. saw you on SC... how you worked that mannequin's cock.. slow licking sucking throating eyes at camera... well, fuck! ", 'pos'),
    ("#mother daughter porn sex on her period videos https://t.co/DDXgdOzyJE", 'pos'),
    ("My pussy is out of control! Help me! Im here ; https://t.co/j1JwJzEW9o. https://t.co/iurWdnQDKt", 'pos'),
    ("#wife likes pussy sexy aunties photo https://t.co/OE3KLq7WJM", 'pos'),
    ("#natalie porman nude granny creampie pussy https://t.co/6LVwY2cxFt", 'pos'),
    ("#men giving oral to women porn max hardcore fuck teen https://t.co/bMst0n1eG2", 'pos'),
    ("#naughty amateur video white women indian men sex video https://t.co/eS7uOtBDPM", 'pos'),
    ("These niggas pussy https://t.co/CTisL5Mg61", 'pos'),
    ("mexican granny loves to engulf dick and plays with her dildo https://t.co/r6avwH7ZOs", 'pos'),
    ("#girls nude doctors cartoon sex lesbian https://t.co/10swLhvwLX", 'pos'),
    ("man fucking a gorilla sex pictures #naked men video https://t.co/IsyUB1P1oj", 'pos'),
    ("#mariah karey nude tranny porn tube https://t.co/DXs8mxXIJN", 'pos'),
    ("free sex piture #nude midigit girls https://t.co/TJbLTCBMEu", 'pos'),
    ("Gonna clean the whole house brb https://t.co/55vhpR2dRF", 'pos'),
    ("I hate everyone who has had sex in the last month.", 'pos'),
    ("Amazingly teen honey Nataly stripping and showing her skinny pussy https://t.co/dBUKMZfCOC https://t.co/eXsAKLNjj0", 'pos'),
    ("jaimee foxxworth porn #simi perla porn https://t.co/mVgHtnIjOJ", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/3jAyy8yp1D", 'pos'),
    ("#Gay More Best Gay Porn Sites or Gay Porn Pay Sites https://t.co/dx0qaksbU0 https://t.co/rSUpSEcIl7", 'pos'),
    ("middle eastern women naked #the girl next door movie sex scene https://t.co/w2TAop6KNh", 'pos'),
    ("On point. https://t.co/GquAQhUcCg", 'pos'),
    ("#kissing porn video ivf sex selection https://t.co/x49LUgFRSy", 'pos'),
    ("#girl smoking weed and having sex sex villa 34 https://t.co/bkVMAK2bZ6", 'pos'),
    ("#eating out girls pussy pussy juice energy drink https://t.co/iHRd0v5yZz", 'pos'),
    ("#directsex video fre anal porn https://t.co/a2Na5xWndX", 'pos'),
    ("#do girls like anal sex sexy bitches pussy https://t.co/dOX6S2FJkK", 'pos'),
    ("@ MF AARON https://t.co/u37eA6d76E", 'pos'),
    ("#indonesian women porn free nude booty https://t.co/81SwgNrOAp", 'pos'),
    ("#big bubble butt brazilian orgy 5 unblocked sex games https://t.co/M5yO9igFbL", 'pos'),
    ("#hairy pussy juice amateur teen us https://t.co/8tmSa8e5NE", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/bOOLMcC77e", 'pos'),
    ("#sleeping videos sex yellow bone solo girl porn vids https://t.co/kiBWQ1p3Y7", 'pos'),
    ("twin lesbians porn https://t.co/ZTcPvGfyfU", 'pos'),
    ("#slow gentle sex wwwfreechubbygirlsex https://t.co/HwpR9r538I", 'pos'),
    ("@VincentGreggEP @Scavino45 @POTUS I did and I saw a beautiful -- sorry your a dick - but you already knew that didn't you.", 'pos'),
    ("#adult jobs from home ay papi sex comics https://t.co/0W8aIiv56E", 'pos'),
    ("cyber sex group https://t.co/VZWAmNK7pa", 'pos'),
    ("Amazing raven haired teen honey Melinda sucking a giant dildo with lust https://t.co/FtKT4M6tAu https://t.co/8LIfVIgy2O", 'pos'),
    ("Meet someone tonight for sex &gt;&gt; https://t.co/C8vn7CwtMa https://t.co/T36CX6LlrZ", 'pos'),
    ("Mommy need dick. My pussy is hot! Im here  ; https://t.co/IVYVuGveZb. https://t.co/RTGLjEYMEp", 'pos'),
    ("Don't speak upon something you don't have facts on you dick head", 'pos'),
    ("#free betty boop porn hemroids and anal sex https://t.co/hNEpbAkY6g", 'pos'),
    ("sex blood videos #toon porn vidoes https://t.co/qoC7NTO4JW", 'pos'),
    ("tranny porn online https://t.co/6X9c9x0uuE", 'pos'),
    ("A disturbing sex trend called 'stealthing' is on the rise  https://t.co/WynUAfKMI7 via @usatoday", 'pos'),
    ("#Gay amateur-gay-sex-videos-only:(via A curved big one) https://t.co/8G20fJfhsZ https://t.co/DDPSSdvwR2", 'pos'),
    ("@randygdub @pixelatedboat oh lol who could have guessed the guy was a huge pussy", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/T930684GHx", 'pos'),
    ("#sex on her period videos hot sex gallerys https://t.co/KFQ3PVDe5v", 'pos'),
    ("#the girl next door amatuer sex the girl next door naked 2007 https://t.co/bh9NkcGdKs", 'pos'),
    ("#vannesa hudgens having sex va sex https://t.co/bHiVRZMYvR", 'pos'),
    ("@xxxJadeNixon @kj_fetishmodel It was mostly about the sex scenes.I know I physically can not perform to the best of... https://t.co/2hb9MNetV1", 'pos'),
    ("what you prefer the most... sex ending in creampie ...  W h y https://t.co/HnBqpI9tWu", 'pos'),
    ("check sex offenders in my area #girl gets fucked by her boss https://t.co/CVZ8qMr6Gs", 'pos'),
    ("Same reason you tweeting about my woman https://t.co/RM98i2hd05", 'pos'),
    ("#sex scenes tube nuderewiew https://t.co/314dEK0twX", 'pos'),
    ("#biggie and lil kim sex malaysian sex sites pictures https://t.co/ytvjCt4AzC", 'pos'),
    ("@tsunbiscuit suck my dick SMTIV is a good game", 'pos'),
    ("@_ShowTime___  bro ass tweaking  https://t.co/hW6EnaNknw", 'pos'),
    ("#hot sex on you tube granny anal action https://t.co/7GubK0fBNB", 'pos'),
    ("#hotwomenhavingsex #game sex #white #analsex hairers #boobs toprated https://t.co/z9xUNuVPlw", 'pos'),
    ("#duke of hazzard girl gets naked sex manga cartoon https://t.co/oGeWNBULdm", 'pos'),
    ("free homemade ebony porn #how to meet people for sex https://t.co/fNKeqZIDGY", 'pos'),
    ("#black pussy thick free sex position photos https://t.co/NrPg2QeTHC", 'pos'),
    ("#free porn videos blondes red haired women sex teacher https://t.co/OS7501MU0Y", 'pos'),
    ("hd porn vids view the full clip here &gt; 2 &gt; https://t.co/OUWP22axVC https://t.co/xvdmnYWF7g", 'pos'),
    ("free porn viedoes #black bi sexual men https://t.co/A1g9nGSTRl", 'pos'),
    ("My pussy is out of control! Help me! Im here ; https://t.co/s5vdUa26mH. https://t.co/bkhunuSJHJ", 'pos'),
    ("Even when I am gone @RPPerson_, @LBSasha92 and @SDLiveQueen will always remember this cock.", 'pos'),
    ("Brandy Smile is a sex pro and heres the proof https://t.co/t23Mua7O6P", 'pos'),
    ("@prikybastard @kingchris2cool @ChubbymomChubby @bbwpornworld @chubbychaserau @Benito71508950 @lovebbw22... https://t.co/7Z1XuPSpwv", 'pos'),
    ("#home wife sex videos shaved chubby pussy https://t.co/uYIZ5aROdT", 'pos'),
    ("hd porn vids view the full clip here &gt; 2 &gt; https://t.co/RVxBm1fA3l https://t.co/R7wZNxYugp", 'pos'),
    ("#princess peach porn games hardcore lez sex https://t.co/y0yXIORz7P", 'pos'),
    ("females be gay until it be time to eat that pussy. u hoes stay flexin lol", 'pos'),
    ("#youtube for porn donky girl porn images https://t.co/uVPR34eRNy", 'pos'),
    ("@RUSKlN First blowjob bots, now this", 'pos'),
    ("HornyHolly is currently Live Free Chat #pinay #Filipina #Philippines #Asian #pussy #sex #horny #ass #booty https://t.co/3NVNx50g3N", 'pos'),
    ("@TalkingArrow Supes was a dick in that episode though.   And Cap getting damaged by that vault Superman dropped on him was bullcrap.", 'pos'),
    ("I forgot what a pussy feel like", 'pos'),
    ("#fucked getting pussy teenage adult erotic reading https://t.co/6ZVZy6Xnl3", 'pos'),
    ("#arabic university girls fuck milf naked sex https://t.co/3dr8wXkaKe", 'pos'),
    ("#chinese girl sex with oldman secretary having sex with boss https://t.co/TiFxzsBQyZ", 'pos'),
    ("#free porn and sex movies adult and teen porn https://t.co/6yF2YyS8wv", 'pos'),
    ("Leave the toilet seat up https://t.co/PVToa8xHeq", 'pos'),
    ("you're starting to sound like a all talk pussy bitch. it hasnt ever been about no action whatsoever ", 'pos'),
    ("Horny Melissa Moore gets fucked on the kitchen counter - Naughty America  [#porn, #explicit]  https://t.co/dPBDc7JRZs", 'pos'),
    ("#21 sex video sexy girls greek ass photos https://t.co/fIuuEvS4pX", 'pos'),
    ("@ChaosApathy @Cigar2 @VICE Sexist, they are all dick shaped", 'pos'),
    ("#older women having sex sex and city girl porn tube https://t.co/e3xC7xyZ7h", 'pos'),
    ("#teen malay naked free fuck porn clips https://t.co/moH3ta1Jy8", 'pos'),
    ("#brother and sister hentai porn panjabi girl sex video galley https://t.co/CPZB26IM5W", 'pos'),
    ("#seymour butts porn hot guys fucking each other https://t.co/VfcCs2ksaT", 'pos'),
    ("Brunette latina pornstar Ice La Fox rides a big dick and swallows jizz https://t.co/RQjRHdJKLB https://t.co/ujm9Zojbx9", 'pos'),
    ("#teaching how to eat pussy girl in thigh high https://t.co/rwgMSxqcGG", 'pos'),
    ("Bitches still comming on Facebook to talk about sex  fucking thots ", 'pos'),
    ("#syria nude girl pics porn essex girl pictures https://t.co/Q0Y5DKlVhG", 'pos'),
    ("Red haired teenage hoe Trisha Bangs gives handjob on her knees https://t.co/L7UT6rMGxU https://t.co/vph9XAHJfs", 'pos'),
    ("The porn jawn wit the Wu Tang W on her ass &gt;&gt;&gt;&gt;", 'pos'),
    ("#brutal fetish porn girls on girl fucking https://t.co/fYH31l8B9R", 'pos'),
    ("#pissing in pussy video naked women on video https://t.co/WGIRReLh0m", 'pos'),
    ("#hot sex gallerys silhouette images stoner https://t.co/KxHTa2JfRb", 'pos'),
    ("Remember when Scott Kurtz dared me to go to the Comic Expo to talk shit to his face like I wouldn't actually do it https://t.co/9PuBEu1Pzi", 'pos'),
    ("give her the dick and I'm outta there", 'pos'),
    ("#anonymous sex story lesbian college porn https://t.co/5oYDNTt3Wl", 'pos'),
    ("late period after sex https://t.co/RndwX3JfkH", 'pos'),
    ("being out of touch sucks. but what sucks more? is the people that wont get off my fucking cock", 'pos'),
    ("#XXX #sex best porn clips updated daily for full videos &gt;&gt;&gt; https://t.co/8DgzeJg8fx https://t.co/ARKlSAq4n2", 'pos'),
    ("Small Cock Man Teased and Abused in Locker Room! - Part 3... https://t.co/EVDRtoUWpd #FACESITTING via @clips4sale https://t.co/6AN26ud3Hd", 'pos'),
    ("4215 Click: https://t.co/Q7jm0hOWmQ #fuck #fucks #porn #video #videos #vidz #XXX #free #fine #feel #Fucking #Fucked #fantasy #fantastic", 'pos'),
    ("She need some pussy https://t.co/QzSdKRwETn", 'pos'),
    ("Shakira88 is currently Live Free Chat #pinay #Filipina #Philippines #Asian #pussy #sex #horny #ass #booty https://t.co/xWJsnye89M", 'pos'),
    ("# foto sexy italian women bare boobs and pussy https://t.co/etTk50QOTi", 'pos'),
    ("@LoveHateSexCake Smear a whole essay of sex on my chest", 'pos'),
    ("#swimming classes for adults college girl video sex and naked https://t.co/7oAWDYUEjC", 'pos'),
    ("#sonia baghdady nue playboy fuck porn video https://t.co/XPMra2XAV4", 'pos'),
    ("#XXX #sex best porn clips updated daily for full videos &gt;&gt;&gt; https://t.co/TGAs4BXPv4 https://t.co/nemIVQ3LbD", 'pos'),
    ("#xxs porn nude athletes pictures https://t.co/p41ojrgEDK", 'pos'),
    ("#melisa nude video lesbian sex free vids https://t.co/ntz3yzJaie", 'pos'),
    ("video technique et position de sex porno #ebony pussy and tits https://t.co/raG6SjFYp1", 'pos'),
    ("Chief State's Attorney's Office Reviewing Choate Sex Abuse Case https://t.co/GrseOR1yHd", 'pos'),
    ("#milf naked sex free bachelorette party porn https://t.co/Hef1oROiHh", 'pos'),
    ("hardNwetcouples is currently Live Free Chat #filipina #pinay #pussy #booty #ass See More Pinay Whores -... https://t.co/tEJ9nVUFwH", 'pos'),
    ("#horny women wearing stockings desperate house wifes porn https://t.co/JJSxDSEQVE", 'pos'),
    ("naked girl sex boot camp stories https://t.co/y6BKUkHe2T", 'pos'),
    ("#non-nude porn movies best things to do during sex https://t.co/aBEXxhZMQW", 'pos'),
    ("#dreadlock girl sex extreme sex show https://t.co/ATH0ZEmOqf", 'pos'),
    ("thought she was dancin' on that dick, that's clip !!! Bitch ", 'pos'),
    ("Virtual Reality Sex Dolls Can Be Programmed. Is The End Of Prostitution Next? https://t.co/Y1UxbUgUnC", 'pos'),
    ("#twinks first sex sex with rachel https://t.co/7qGwWKptun", 'pos'),
    ("#game sex scene adult channels sopcast https://t.co/zN85mq8J9W", 'pos'),
    ("farting girls porn https://t.co/tigtwIlhHd", 'pos'),
    ("#porno pics gallery sex grill https://t.co/QDuqIS3RnC", 'pos'),
    ("japanese guys having sex https://t.co/ugOV5lYMW8", 'pos'),
    ("#marathi girl fuck video teacher sex with students videos https://t.co/p6UsKD01cN", 'pos'),
    ("#porn felony full figure sex https://t.co/zkwBpOfQcL", 'pos'),
    ("#boy sex site pictures of naked guys for girls https://t.co/YVK8bICYUg", 'pos'),
    ("3869 Click: https://t.co/Q7jm0hOWmQ #fuck #fucks #porn #video #videos #vidz #XXX #free #fine #feel #Fucking #Fucked #fantasy #fantastic", 'pos'),
    ("#porn with big dick free porn kee https://t.co/bpUzvd7zFQ", 'pos'),
    ("#finger in ass sex dump sex https://t.co/11ek0B66MW", 'pos'),
    ("#hot rough lesbian sex free sex people https://t.co/mCzXJXWvwW", 'pos'),
    ("LADYBOSS77 is currently Live Free Chat #pinay #Filipina #Philippines #Asian #pussy #sex #horny #ass #booty https://t.co/VRj6ecbqNn", 'pos'),
    ("#orgies #schoolsex #boobsex #handjob #handjobs #hottie #hotsex Follow opfans88 for best cam girls https://t.co/JewXJsWTsY", 'pos'),
    ("#rate my shaven pussy profesionalgirlsnet https://t.co/H5hcm2qifr", 'pos'),
    ("#totally naked guys mythbusters porn https://t.co/ErNc5GRGSh", 'pos'),
    ("#of naked teenaged free tanned porn https://t.co/FUZXeXpoES", 'pos'),
    ("#doctors having sex with patients videos sex slave training stories https://t.co/tPzA5OPkR3", 'pos'),
    ("sweetlove18 is currently Live Free Chat #filipina #pinay #pussy #booty #ass See More Pinay Whores -... https://t.co/nHqbqz2GP7", 'pos'),
    ("#sexy women athletes free photo sex fane animation https://t.co/Yym1RrgLj7", 'pos'),
    ("girls making and having sex #dominican girl nude https://t.co/wgCL4broQr", 'pos'),
    ("girls sex strange objects https://t.co/3Mz8wMb8bs", 'pos'),
    ("Babes - Lola Taylor - Shades of Kink 2017/FullHD / Porn clip, Big Asses, Big Dicks, Hardcore, Oral, Orgasm, PornStar https://t.co/i5rYHVBWQP", 'pos'),
    ("free videos of naked kerala boys #unattractive teen porn https://t.co/EWWJLUJxwQ", 'pos'),
    ("#goku nude white whore porn https://t.co/WkXy4LUqSn", 'pos'),
    ("I miss eating Chanel's pussy", 'pos'),
    ("#submit girlfriends for vip how do boys and girls have sex free video https://t.co/K2nHU5YbxX", 'pos'),
    ("russian familyporn #pussy lickin pics https://t.co/f8W3Ywi2FB", 'pos'),
    ("@vixcontango Stop watching so much porn.", 'pos'),
    ("#procedure of sex between men and women islam afghanistan girl fuck https://t.co/g00htPnl1U", 'pos'),
    ("#college girl on girl sex castro porn tube https://t.co/mg3YQNQytF", 'pos'),
    ("#what is the importance of sex homemade naked girl pics https://t.co/f8ZTF8ldMI", 'pos'),
    ("@AFrenchForTrump @thefinn12345 @JoeLowsac318 @TheFunnyRacist @Fuhrerious1488 Jesus someone's really friendly with their daddy's dick eh?", 'pos'),
    ("#bodystockings porn the little mermaid sexy https://t.co/aZTqCQdRJI", 'pos'),
    ("7 Awesome Sex Moves for Your First Time https://t.co/C2CC9wsjIh", 'pos'),
    ("#wild sex thumbs hard sex videoes https://t.co/L96Gvr7RHW", 'pos'),
    ("#free bachelorette party porn dry humping sex lesbian stories https://t.co/bDJxhkZ4TU", 'pos'),
    ("@taviaajaay Pretty sure yo moms didnt raise a pussy so thug it out shawty", 'pos'),
    ("#naked pakistani girls the us sex https://t.co/vJ6znW7liE", 'pos'),
    ("#bare boobs and pussy spanish women sexy https://t.co/cJw6lp3MQU", 'pos'),
    ("Superb chocolate nymphet Aryana Starr smoking and slurping a huge black cock https://t.co/1utFS7F2BP https://t.co/mkNr2wOjwa", 'pos'),
    ("LovelyFuckBABE is currently Live Free Chat #pinay #Filipina #Philippines #Asian #pussy #sex #horny #ass #booty https://t.co/M3zU5NoxIT", 'pos'),
    ("#nude kendra wilkinson pics classic porn free https://t.co/2EJ0E2XA3S", 'pos'),
    ("#swidish teen lesb sx michelle johnson sex scene https://t.co/FPOfVkRrE2", 'pos'),
    ("dads dirtygirls sex pic free #cock ring sex toy https://t.co/oIj4JqycFG", 'pos'),
    ("Naughty mom wanna fuck! My pussy is HOT! Im here ; https://t.co/TsrzYnAURY. https://t.co/fCh4mgVwV8", 'pos'),
    ("#top rated porn vids sri lankan girls virgin https://t.co/9izsP3AxrV", 'pos'),
    ("#free daily amiture sex sites christine cali nude https://t.co/K6FvASh2z1", 'pos'),
    ("treety x dick drop offs&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;", 'pos'),
    ("Remember when everyone said Pence was an idiot for refusing to be alone with a woman without his wife? #PenceTwitter https://t.co/UryFsp7Qyw", 'pos'),
    ("#semi nude man free asian teen porn gallery https://t.co/Va0HPloLQD", 'pos'),
    ("10 Sex Jokes On The Simpsons You Might've Missed As A Kid https://t.co/KToilwEuEx", 'pos'),
    ("#fuckingmachines #sex hits #fap #sabadell aarhus #pornoshack basketball https://t.co/E2FcofmMt8", 'pos'),
    ("These 12 Famous Celebrities Reveal Their Embarrassing Sex Scene Moments https://t.co/vc3bY4Rhkn", 'pos'),
    ("#any free porn site free naked dance hong kong https://t.co/boPYhFoPRF", 'pos'),
    ("#ghanaian porn women nude site on cake movie https://t.co/riKxjUdpkr", 'pos'),
    ("#free group porno movies thai blowjob pics https://t.co/BLtutnvrRJ", 'pos'),
    ("WANTEDHUSBANDZ is currently Live Free Chat #filipina #pinay #pussy #booty #ass See More Pinay Whores -... https://t.co/8htfwLV151", 'pos'),
    ("#free pic of teen having sex pornstar candy manson https://t.co/XiAbmtiWYK", 'pos'),
    ("Get that wretched pussy away from me.  https://t.co/9SH7uU24ew", 'pos'),
    ("#fuck women lake havasu angelique morgan free porn video https://t.co/EJfQKz14xC", 'pos'),
    ("#sex on pics single sex classes pros and cons https://t.co/0qWVuXalIQ", 'pos'),
    ("sex men pic https://t.co/lNdb1YoaN5", 'pos'),
    ("14 Shocking Sex Confessions From Celebs https://t.co/WSsTYfSvsD", 'pos'),
    ("granny sex gallerys https://t.co/DP9OTRzEDq", 'pos'),
    ("#pornstar vision tob sex https://t.co/gjfrg0dN3N", 'pos'),
    ("pussy @9layamade https://t.co/WVxz8hq0da", 'pos'),
    ("Mommy need dick. My pussy is hot! Im here  ; https://t.co/rF5QPfyXWU. https://t.co/7hngLvg8g1", 'pos'),
    ("#teenage porn trailers green sweater office sex https://t.co/0FrcbHeo0P", 'pos'),
    ("Retweeted Sex NotesTM (@RealSexNotes):  s/o to the boyfriends who love their girlfriends unconditionally while... https://t.co/w52ItNqiu6", 'pos'),
    ("#amateur allure free download bodypainting pussy https://t.co/LPJEZdzkUS", 'pos'),
    ("#energy for sex marvel girl porno https://t.co/c2eVDn10BQ", 'pos'),
    ("Retweeted Sex NotesTM (@RealSexNotes):  s/o to the boyfriends who love their girlfriends unconditionally while... https://t.co/P0zdWqsCAD", 'pos'),
    ("nativeamerican porn #miley cyrus being naked https://t.co/qsLn7jTw1g", 'pos'),
    ("#jessica biel free nude download full sex movies free https://t.co/AQcUWlOxTZ", 'pos'),
    ("#emo girls porn pictures porno party girls com https://t.co/tNBeq2dh79", 'pos'),
    ("Round assed blondie milf Laura Monroe jumping a huge dick on the couch https://t.co/I8hYlWJCSM https://t.co/qHZsMvCGS4", 'pos'),
    ("Single men and women reveal their biggest sex and dating turn offs: https://t.co/sO2Zeo1iTA https://t.co/8btIAceYNf", 'pos'),
    ("Excited lesbians Gia Naughty and Rosanna Rose licking their sexy tongues and screwing a big cock on the couch... https://t.co/UxI97Quc8T", 'pos'),
    ("sapphic erotica orgasm #shaved pussy sexy https://t.co/RgyQUPJktV", 'pos'),
    (".@hotgirlswanted A sex worker once told me something about her name. I won't share it here. I kept it secret out of... https://t.co/BRontFTzQ5", 'pos'),
    ("#hard core sex videos charles barkley pussy https://t.co/U14r8Riwya", 'pos'),
    ("@KTVU If you don't even know the person very well, then maybe don't have sex with him/her? I know, crazy right?", 'pos'),
    ("#hardcore bands 2009 free mature group porn https://t.co/BdacDvGDna", 'pos'),
    ("@holyaine Do you eat pussy", 'pos'),
    ("#massage sex sites british hot saxi women https://t.co/JKyyROieBf", 'pos'),
    ("#essex bedding milfs free sex https://t.co/SNUMjsDPk7", 'pos'),
    ("HornyLovelyxxu is currently Live Free Chat #filipina #pinay #pussy #booty #ass See More Pinay Whores -... https://t.co/Qs0w9uIGm0", 'pos'),
    ("online adult shop #older women porn movie https://t.co/53fgDGgGYs", 'pos'),
    ("#big hairy pussys kim kardasion sex https://t.co/Zcd9fXcAzV", 'pos'),
    ("hd porn videos for the full clips visit our site &gt;&gt; https://t.co/kZvc7PcSut https://t.co/evZtePXrLE", 'pos'),
    ("Mommy need dick. My pussy is hot! Im here  ; https://t.co/Dxn9xAic2Y. https://t.co/l42WxFaUsB", 'pos'),
    ("@arialgallego_ So u gone act like u ain't suck his dick and fuck him whenever he want to ", 'pos'),
    ("#the sexiest woman alive naked pic close up pussy creampie https://t.co/4ZN4Y7KU7P", 'pos'),
    ("hd porn videos for the full clips visit our site &gt;&gt; https://t.co/XMc5ro7eyd https://t.co/SnJLZXP48Z", 'pos'),
    ("#max hardcore rebeca linares free black pussy white dick https://t.co/j8kOK8vHUL", 'pos'),
    ("#pictures of mom and son sex free beast porn movies https://t.co/gC9kYhZ9BJ", 'pos'),
    ("#dry humping sex lesbian stories sex positions 3d https://t.co/pKtNgNPUQS", 'pos'),
    ("#naked women in socks girls pooping during sex https://t.co/UkvnP4rwUO", 'pos'),
    ("Let me get off Bruno dick &amp; go to bed .. I'm in here acting a fool ", 'pos'),
    ("'Why I Love My High Sex Drive' https://t.co/02wGZOk6wE via @womenshealthmag", 'pos'),
    ("#hairy pussy free clips your adult blog https://t.co/XgPVb0yE4m", 'pos'),
    ("#free porn sex video clip nicolle tom porn https://t.co/ZWcYKEo4U5", 'pos'),
    ("#porn for old men tall naked women pictures https://t.co/C7MpnbLr2j", 'pos'),
    ("Shoplifter Anastasia Rose bangs in her tight pussy: #young Shoplifter Anastasia Rose bangs in her tight pussy - Ich... https://t.co/xP6XllmrMf", 'pos'),
    ("@black_becky34 Baby you got my DICK harder then a motherfucker. You sexy bitch. Excuse my vulgar.", 'pos'),
    ("According to @FavstarOfTheDay all my tweets are porn,so don't bother checking my tweets out", 'pos'),
    ("#ebony homegrown porn bakugan girls naked https://t.co/Vmc0QTou9y", 'pos'),
    ("Full Movie: https://t.co/oAXO0ThVS8 Thirsty girlfriend goes for some cock th... Add me on snapchat: mycuteass18  https://t.co/Uzeg1LvBrm", 'pos'),
    ("the little mermaid naked #pain porn pics https://t.co/Z8pW2VxvBx", 'pos'),
    ("#blowjob singles with #hotporn #boobs true https://t.co/pkyNb5cKp4", 'pos'),
    ("#is sex a need teen lesbian land https://t.co/6b5bicFkK5", 'pos'),
    ("Papi @Kadiret75926370 come see my pussy wet https://t.co/LiMOUWEg2s", 'pos'),
    ("@salvato75819316 salvatore Howdy My partner and i invite you to this particular adult porn cam totally free register Click on my profile.", 'pos'),
    ("#indian smart slim girl porn video image of junior miss nude pagent https://t.co/XYtxz9n05F", 'pos'),
    ("#teen sex iaranian small nude teen porn you tube https://t.co/4IaCoRppMr", 'pos'),
    ("I thought your girl was supposed to be your best fr...  I don't have a girl bud  https://t.co/rzfsVEWGy2", 'neg'),
    ("@FoxNews @brunelldonald No. Can't find a way to govern between these two branches. Colossal, communal fail.  This p... https://t.co/M4p0JlFt0W", 'neg'),
    ("These bitches fuck for a bag, and you niggas gonna go out sad !", 'neg'),
    ("I was bout to add my 2cents but I forgot houston a state https://t.co/TLIwZMsJpT", 'neg'),
    ("sigh.....when will it be my turn to get punched to death by a huge gorilla https://t.co/u2K1Lz04Jc", 'neg'),
    ("Boxing is a bad sport", 'neg'),
    ("What a round!!", 'neg'),
    ("Now Playing: Pat McMullan - Read In Bed Mp3 / check: https://t.co/VHHbFtmRD2", 'neg'),
    ("@Millard_Filmoor @TheDemocrats @GOP The Republicans exempted themselves from their Bill, they prefer Affordable Car... https://t.co/5NOJQzTzFB", 'neg'),
    ("Need another 7 rounds like that", 'neg'),
    ("@lexiesummerrs @kris10engels Call them Lexie!", 'neg'),
    ("I forgot Adrian told me to kill my dad", 'neg'),
    ("My Twitter worth is: $578.55  Find yours with https://t.co/LTNcNa10I7  . https://t.co/Zbw3oEAbXB", 'neg'),
    ("@timmaughan Nobody wins except the people who were already always winning. Nothing changes. Everything sucks. Nothing is ", 'neg'),
    ("@tjrnichols Sorry no I spent all my money on booze last night.", 'neg'),
    ("My sex drive rn is type crazy ", 'neg'),
    ("I'm gonna keep working hard https://t.co/TQsX8ND3jN", 'neg'),
    ("it's best i not say anything right now.", 'neg'),
    ("@SmallSoftJimin omg thank you !  I love it too haha yw", 'neg'),
    ("@stanfordburke Get a life", 'neg'),
    ("i love him so much  https://t.co/LUulytRJwc", 'neg'),
    ("well, I guess that is better than playing golf and wasting time and/or tax payers money #100DaysOfFail... https://t.co/OEDDt3NSxV", 'neg'),
    ("@ChaseMartin222 I've never been there", 'neg'),
    ("@EmilyThornberry Wolf in sheep's clothing ", 'neg'),
    ("WHYS MY WIFI GONNA PLAY UP NOW", 'neg'),
    ("Joshua is fucked ", 'neg'),
    ("@EricLloyd Idk about all that but well see", 'neg'),
    ("@Emaniceman2026  that wasn't about you but if the shoe fix", 'neg'),
    ("Signs Vulcan sketch: Larry Quill's alter ego https://t.co/jU7huPvekF", 'neg'),
    ("This fight is mad. Come on AJ man bring it fucking home", 'neg'),
    ("@LeoDiCaprio Which jet will you be flying to it in #Hypocrite?", 'neg'),
    ("I woke up from my nap thinking it was my birthday, I feel played af ", 'neg'),
    ("Barometer 1000.8hPa, Falling slowly Temperature 10.9C, Falling Rain today 0.0mm Wind 0.0mph NW Humidity 59% UV 0 SolarRad 0W/m2", 'neg'),
    ("The Who Endless Wire https://t.co/24RkUn1lBI", 'neg'),
    ("Pfff what a round that was", 'neg'),
    ("@debiowens Out of the mouths of babes...", 'neg'),
    ("I liked a @YouTube video https://t.co/mEGQQZtPy9 DIVINE LASSO!| Dragon Ball Xenoverse 2 DLC Pack 3 Super Sayian Rose Goku Black", 'neg'),
    ("Over under on rounds left in this one? two?", 'neg'),
    ("Having an icream and crying #livingmylife", 'neg'),
    ("Complacency is the cornerstone of many #advertising strategies. How about yours? #rva https://t.co/p5BLHCvCUp", 'neg'),
    ("This way she has, is truly amazing. #FFXIV https://t.co/Xuywa3nDFp", 'neg'),
    ("Will we get the 'Regret In Your Tears' video tomorrow or on Monday? What do you think? I love u btw ... https://t.co/YDeu13g98G", 'neg'),
    ("Man .. on everything ..that Pure White Hennessy like 10X stronger than the regular  somebody son would literally be begging me to stop ", 'neg'),
    ("need someone to help me with duel arena clue on old school pls :(", 'neg'),
    ("I'm praying for you AJ", 'neg'),
    ("Joshua is beat hopefully the 7th", 'neg'),
    ("Have you noticed when a rich guy post something on fb. They all rush to comment, 'its true boss' or 'you are... https://t.co/7mK5hjUdu3", 'neg'),
    ("https://t.co/vcvL0v74ab     Game 3", 'neg'),
    ("Kaaya to the lions", 'neg'),
    ("My favorite song right now! Checkout    'Sweet potatoes' by @Aprilsingz ft @b2lofficials https://t.co/5w2gof46nF https://t.co/yu1kUd6w3R", 'neg'),
    ("shes so fucking cute https://t.co/LF7H7oKzw4", 'neg'),
    ("We have all your favorite protein foods &amp; @PerdueChicken packed into one salad recipe #PerdueCrew #Promotion -... https://t.co/jloVY7ZZD0", 'neg'),
    ("@Conclusit That's why I stopped watching after I discovered the 5Ds sub and manga like holy shit.", 'neg'),
    ("Massive heart from klitchko there ", 'neg'),
    ("@s_dog @GlockLady @Yvon727 Thank you for the SO Spot", 'neg'),
    ("when you're falling in a forest and there's nobody around", 'neg'),
    ("@Jamie_1807 That sounds amazing! ", 'neg'),
    ("The Radium Dial Painters https://t.co/a4x8s8JqLH https://t.co/MoFC11weiJ", 'neg'),
    ("I praise Thee to the depth &amp; height my soul can reach. #FaithfulBelieversMCGI", 'neg'),
    ("Brendan Rodgers has gone and won a treble for Celtic in his first season.", 'neg'),
    ("Time will tell.", 'neg'),
    ("Kill him", 'neg'),
    ("@Lee_Rich13 @Dee_DeeJ14 you can't help but dance when you hear that...", 'neg'),
    ("I liked a @YouTube video https://t.co/r1cVAZRFW0 2017-2018 Erin Condren Life Planner PREVIEW!", 'neg'),
    ("Urge H&amp;M to stop selling animal skins: https://t.co/DZb65XKhIm", 'neg'),
    ("Musical instruments and studio accessories | Clas Ohlson - https://t.co/9Pr6TnBT3z https://t.co/b1LjomOg32", 'neg'),
    ("I stg if my mom doesn't come pick me up I'll throw hands", 'neg'),
    ("@smcosta1969 @CNNPolitics Ah, come on Tucker, we love watching free entertainment. Honestly, my friends and I watch CNN just to get a laugh.", 'neg'),
    ("Holy shit that round though #JoshuaKlitchsko", 'neg'),
    ("I just earned the '2X (Level 2)' badge on @untappd! https://t.co/QIjoFPXEJi", 'neg'),
    ("slorp https://t.co/aeVLQmEMTH", 'neg'),
    ("President Trump denies stories that the White Home is in chaos - https://t.co/DWlXFm38O2 https://t.co/9VWoGi19tb", 'neg'),
    ("I liked a @YouTube video https://t.co/0xZbM4tNGz FULL FACE OF *ADULT* CANDY", 'neg'),
    ("@lexxtorress thanks I know", 'neg'),
    ("I'm sinning on social media and I'm saying you can too. https://t.co/t7rWqyYhAY #ContentMarketing", 'neg'),
    ("@JoeNBC @seankent @nytimes stupid is as stupid does. Don't like Bret Stephens but I still need the NY Times.", 'neg'),
    ("@BBCFOUR @thealarm @GarethJonesTV A like from @garethjonestv (blushes). I guess we all had big hair at some time or other, back then, lol.", 'neg'),
    ("My favorite song right now! Checkout    'Sweet potatoes'' by @Aprilsingz ft @b2lofficials https://t.co/TNOYf72Z8S https://t.co/WsrwsbCFtQ", 'neg'),
    ("My fucking heart is somewhere else ", 'neg'),
    ("overweight teen adolescence is https://t.co/OvkVe9ujDB", 'neg'),
    ("Recorded #I Believe Wbgv on #SingSnap #karaoke https://t.co/t31oPIElsR", 'neg'),
    ("Joshua gunna get stopped here", 'neg'),
    ("Japan's Abe warns of 'confusion' without UK/EU Brexit deal https://t.co/6lTcwwvwMc via @todayng https://t.co/oJ3kbeIpvI", 'neg'),
    ("@GelertClaire @murphythecollie On that basis you will never have money ... ", 'neg'),
    ("2YEON HAPPENED IM CRYING JEONGYEON FINALLY DID IT", 'neg'),
    ("Listen to @flylittleraven MIX **30 MINUTES** by ... #np on #SoundCloud https://t.co/GNpwF7fp5S", 'neg'),
    ("Dakota Skye Quintana and Daniel Quintana I want prom pictures! Hope you have tons of  fun", 'neg'),
    ("De-lic-ious that's the summary @TheMuddlersClub @gdog193 https://t.co/tKimp6xv2z", 'neg'),
    ("I had the most electoral votes of any incumbent president to lose reelection #AlternativeTafts", 'neg'),
    ("@QJaaay scoop some?", 'neg'),
    ("Me as a mom https://t.co/AlMMRayMb3", 'neg'),
    ("mt dificil but @luana_brasao https://t.co/RjB0yFQdNF", 'neg'),
    ("Turn old bottles into beautiful &amp; unique glassware/art you won't find anywhere else with this simple tool - https://t.co/9QLKYhbH51", 'neg'),
    ("Allens one downfall: his hate for horror films", 'neg'),
    ("Going down... https://t.co/jrfhWoretu", 'neg'),
    ("In Boston: End of the 4th -- Boston 3, Chi Cubs 2 #RedSox", 'neg'),
    ("idiots are everywhere", 'neg'),
    ("@ChrisJansing Chaotically ? A one page memo is tax reform?", 'neg'),
    ("great minds think alike  https://t.co/VEoxf6s4jk", 'neg'),
    ("Yeah. Every day. In every way. [Via @jjoybrindle] https://t.co/PaszXij6se", 'neg'),
    ("Cumonnnnnnnn @anthonyfjoshua we're all counting on yoooouuuu ", 'neg'),
    ("Man threatens female student via text before shooting gun through her window - Good4Utah https://t.co/5AqTd1qX6I  - #Provo", 'neg'),
    ("@kidd_kong78 same ", 'neg'),
    ("@thomps_sarah  thanks stargirl", 'neg'),
    ("My jars of wisdom ought to be filling up soon!  #wisdom #quote #life https://t.co/Kx4X26GR88", 'neg'),
    ("https://t.co/zEDUciE1SE #shoes Mens Nike SB Blazer Zoom Mid Leopard Black White Max Orange 864349-001 sz 9-11.5 https://t.co/gcHfetdeGl", 'neg'),
    ("Define your business goals clearly so that others can see them as you do. George F. Burns #wisdom #qoute #inspiration #motivation", 'neg'),
    ("W/ Vincent Taylor off to Miami will #okstate have multiple draft picks for the first time since 2012 (Blackmon, Weeden, Martin)? 1 Rd to go.", 'neg'),
    ("Hazard on I-75 N #ATLTraffic still delaying traffic 35m more than usual https://t.co/Rg4eqiTpYa https://t.co/Wxl4xJgPN1", 'neg'),
    ("One day, San Francisco is gonna look how the Coliseums in Greece because people will stop cleaning it &amp; the people will move somewhere else.", 'neg'),
    ("Kittanning PA USA - #Home Healthcare Nurse - RN or LPN Opportunity! #SGHAR - Registered Nurse RN - ... https://t.co/wUYQM4SFUk #HEALTH #JOB", 'neg'),
    ("Reading old messages I be like", 'neg'),
    ("#AirportNews Greenville-Spartanburg Airport positioning itself for more growth https://t.co/Q07UGiG6mf #Airports", 'neg'),
    ("@samzo_ 'I must break you.'", 'neg'),
    ("I liked a @YouTube video https://t.co/01BStBU6AJ Car Detailing Tips and Tricks (Bringing an Old Car Back To Life)", 'neg'),
    ("@GggggChhtg I can't use my money from that iPhone I sold till I ship it", 'neg'),
    ("Anyone wanna go to the gym with me later?? Like 8ish??", 'neg'),
    ("@djkaywise Sup, How your side... Follow back, wanna Dm you some stuff", 'neg'),
    ("&gt;The Playboy Diaries: The one-night stand - Rita was tipsy, took my hand and went to her to car to have Sex https://t.co/td9pJQw7rE", 'neg'),
    ("@buteravipors done too", 'neg'),
    ("- Why you bother me when you know you don't want me?", 'neg'),
    ("look at phils camera roll https://t.co/V7vQHOH2f1", 'neg'),
    ("@Steve_Dangle I think the Rangers fans are gonna start talking about squeegee kid now", 'neg'),
    ("Now #Joshua, this is boxing Klitschko take him down Joshua no stamina", 'neg'),
    ("Emirati Nightsky Withington Adv SJ 2017: https://t.co/GjVz8kcGBq via @YouTube", 'neg'),
    ("Thanks  for the follow! Check out my website and contact me if you have any questions. https://t.co/8hWiaUzYYI", 'neg'),
    ("Last year Mariah Carey struggling to lift her giant ring!  #celebrity #celebrities #qotd #gossip #news #fashion https://t.co/BOpUqRwRBC", 'neg'),
    ("Mood  https://t.co/B4DYODTLUd", 'neg'),
    ("Hey :)  on @chaturbate now", 'neg'),
    ("TS4 Abandoned Kids Challenge LP Ep. 17: https://t.co/jBoAZ2rxZr via @YouTube", 'neg'),
    ("A native Burmese customer thought I was also Burmese today. That's a new one", 'neg'),
    ("See how Deep Trekker ROVs are used to regulate the #Aquaculture industry https://t.co/LFcOfECHwF https://t.co/KXs02WfA6l", 'neg'),
    ("@ChecktheStatsAJ @_inVEZtigator What makes you say that? Serious question Ive been busy as hell at work today &amp; yes... https://t.co/etwp0S9lZm", 'neg'),
    ("He actually is https://t.co/SShjAkkqHJ", 'neg'),
    ("@N_landCouncil @LitterGram well this has still not been collected, but then 6 months and street sign in same locati... https://t.co/xsLh0BamVE", 'neg'),
    ("The wonderful @lyciaora surely dances all well, but I hear she's a salsera nonpareil! https://t.co/ixE71USwUA", 'neg'),
    ("John Barnes - 50million price tag shouldn't put Liverpool off in Van Dijk chase https://t.co/lfP9X0G8jd", 'neg'),
    ("@LuckyLamps Parker won't ever get there. There's not enough $ in it for promoters. Who would watch, apart from his mum?", 'neg'),
    ("I remember when I was younger going to the mall and going to @HotTopic and my brother saying 'do we have to? I don\'t like the people there.'", 'neg'),
    ("Imagine what it must have taken to capture these #stunning pictures! #photography  https://t.co/nSXTqHoBtQ https://t.co/7jhFO7zSr3", 'neg'),
    ("My entry for Z in #AtoZChallenge - #ZaanseSchans #Netherlands - https://t.co/Xgtv8VP6jz #TravelBlog #Blogging... https://t.co/LZR2oejzee", 'neg'),
    ("GOLDBERG VS RICK FLAIR'S SON ON WCW MONDAY NITRO [HD] https://t.co/bO4ZeN1mhA via @YouTube", 'neg'),
    ("Wait, Aaron Hernandez Wrote ILLUMINATI On His Wall In Blood AND Wasnt On Drugs Before Suicide? Get The Latest! https://t.co/ahs7S11Wuc", 'neg'),
    ("I want a #LivePD mug @danabrams! Anyone else?", 'neg'),
    ("Joshua will lose tonight!", 'neg'),
    ("Hella high  https://t.co/KpYo7zbUrv", 'neg'),
    ("Joshua doesnt even block smh", 'neg'),
    ("#Joshua showing what we all wondered... he hasn't got the chin shame", 'neg'),
    ("The Latest: Bee's show briefly upstages press corps' dinner https://t.co/XaG8m6Wtuf", 'neg'),
    ("I want more.", 'neg'),
    ("one person followed me // automatically checked by https://t.co/005blU1LJF", 'neg'),
    ("If you wake up feeling decadent on a Saturday, the new Saturday brunch @RodneysCalgary hits the spot. #mmm... https://t.co/9GAM7PUYo8", 'neg'),
    ("Deputy Vuong and Medina Police Chief collecting unwanted medication during today's drug collection event in Medina... https://t.co/9gZ5tQhCPj", 'neg'),
    ("@xxluvleaxx We'll see haha tomorrow is day 2", 'neg'),
    ("Cute bitches can be basic", 'neg'),
    ("Perks of being a hunting guide.... getting a $1300 spotting scope for $850 #TeamVortex", 'neg'),
    ("Don't confuse my personality with my attitude. My personality is who I am. My attitude depends on who you are.", 'neg'),
    ("@Chrisbdg34Smith Democrat is opposite of free choice. You should be free to make own decisions w/o govt force. Prog... https://t.co/Cd4BnQusnO", 'neg'),
    ("No way AJ gonna last this .No way", 'neg'),
    ("@LeonMckenzie1 Man against boy", 'neg'),
    ("Wrote this so long ago, I'd forgotten all about it! #safc https://t.co/0m9kF5azno", 'neg'),
    ("Kenna James Masturbation https://t.co/dQEC97XEIc", 'neg'),
    ("Skjei is really showing up tonight! That was a solid defensive play and a solid goal!", 'neg'),
    ("Lake Regional To Accept MO HealthNet &amp; UnitedHealthcare Medicare Advantage Plans https://t.co/NG5DAtMG2r  - #Imaging", 'neg'),
    ("#Good Luck #Subliminal #Affirmations  Be #Lucky  #Solfeggio #Tones  #Binaural #Beat  #Self Help #Meditation... https://t.co/Y0tLb1GOG2", 'neg'),
    ("Stay down Limey", 'neg'),
    ("No Good Deed should be 'the song' from Wicked, not Defying Gravity. That\'s all", 'neg'),
    ("Found 15 new unfollowers via https://t.co/4WeC2MBcrM", 'neg'),
    ("@DrMarkPickett Ah, maybe so. Although he does begin by saying, 'I don\'t think we should go back...' Either way, it\'... https://t.co/dJeZpDNGYS", 'neg'),
    ("We don't have shit to eat", 'neg'),
    ("Anyrhing could happen", 'neg'),
    ("5 people followed me and 4 people unfollowed me // automatically checked by https://t.co/4PlATckBum", 'neg'),
    ("Just call it the Murdoch Mobile and change Rotherham to Rothemere and you're almost there.. https://t.co/zFP0TF2BbC", 'neg'),
    ("@AngryBlackLady Yay for #teamFEWERDAMMIT!", 'neg'),
    ("The #1 Saturday Night Spot in the RDU! #SocialClubSaturdays @ West Social Club Tonight! https://t.co/WXEdhRMFaV", 'neg'),
    ("secretly filmed NOT my sister in law in masturbation https://t.co/p8mo73Hm0M", 'neg'),
    ("Never thought the rumors would turn to truths", 'neg'),
    ("# love God senes", 'neg'),
    ("Vlad favourite now #j", 'neg'),
    ("https://t.co/LBxcTynGFu A tale of ritual and sacrifice, of goodness and evil and the dark side of power. https://t.co/xxAbObEfn7", 'neg'),
    ("Check Out! ; https://t.co/5NKqZtr890", 'neg'),
    ("@Var___ YOU A MESS", 'neg'),
    ("Military plane crashes in Cuba killing everyone on board https://t.co/BWj02SwOmi - via sitibedotcom https://t.co/1eyXjvOiok", 'neg'),
    ("Browns take troubled Brantley, may release him - ESPN https://t.co/mPxs8QgT8K https://t.co/3GJFJ5jT7E", 'neg'),
    (".@thecatfive:  Miss Bs Take-Out celebrates five years https://t.co/zhqPIQXqUz https://t.co/PRXaYToxGF", 'neg'),
    ("All #travelers should have this! https://t.co/3Q7hsu67F9", 'neg'),
    ("@_native_voyage_ So taurs are cows then", 'neg'),
    ("How did AJ get up!? #JoshuaKlitchsko", 'neg'),
    ("JOSHUA NO STAY UPPPPPP WHATS GOIN ON", 'neg'),
    ("@ynotlater Thanks! Need more nutritious recipes in your life? Go here to see some of our fav's https://t.co/2q6TFBvX44", 'neg'),
    ("Gluten-Free Blueberry Pancakes https://t.co/H2KEqSQe8s", 'neg'),
    ("@sskkyyrraa give me ur biggest boy", 'neg'),
    ("One year already since our first tour in #lebanon ! #sophiedequayandthewg #switzerland... https://t.co/dtUzo2Aony", 'neg'),
    ("@KeeganAllen you will do great tonight xo https://t.co/vjARy9vLki", 'neg'),
    ("#Calm all day long# THAT'S THE WAY IT IS", 'neg'),
    ("this is evil as fuck. disgusting lol https://t.co/Aub2T68EPJ", 'neg'),
    ("I LOVE how Anderson is allowed to stay in net with this horrendous performance. They'll leave him in with a goalie like Condon rink side.", 'neg'),
    ("You like huge tits? https://t.co/Y29sXJfnKF  @douradobot  #sex https://t.co/ExDDczRC0n", 'neg'),
    ("New effort aims to inspire the next generation of pro-environment women candidates   | By @MarkFHand https://t.co/tgrFDhBK38", 'neg'),
    ("Umlaut is a pretty fancy word for what are basically just letter nipples.", 'neg'),
    ("@Seraphable @KAIEYO They hate us nigga lol", 'neg'),
    ("LeBron James Rejected a $10 Million Offer From Reebok When He Was 18 Years Old https://t.co/kwhESEexjV https://t.co/2JxGhX6nPk", 'neg'),
    ("@papaduckchris @56Parkies @SnapperSnafu @Safimod @JediChick79 @esk_100 Seems kind of a drastic way to keep warm...... https://t.co/KgkUsvkDhX", 'neg'),
    ("Man United 4/1 to beat Swansea with Paddy Power T&amp;C's https://t.co/zTx1O6OfmX https://t.co/LhYNb3vohE", 'neg'),
    ("@ThomasCDee @MikeSilvaMedia You're a funny guy....keep dreaming", 'neg'),
    ("No waii", 'neg'),
    ("when ya boo ugly n u love him regardless lol https://t.co/bCjFzc9sjF", 'neg'),
    ("SO YESS HAPPY AND POWERFUL AND PRESTIGIOUS AND SUPER HAPPY BIRTH DAY TO HON @UN SEC,GEN SHRI @antonioguterres SIR!!! AS here dis time as wan", 'neg'),
    ("Tropical drinks are a must on vacation. #Fontainebleau https://t.co/uW3TMkobnb https://t.co/I5dWPhoM76", 'neg'),
    ("it's a matter of time before I get blocked", 'neg'),
    ("Injured Eagles skipper Mikel confirms successful surgery https://t.co/j4jWCH4Adq via todayng https://t.co/QHNrlY44p1", 'neg'),
    ("@aunchull @Jocelynn_Reyes she's referring to the streak her and I literally just lost this morning", 'neg'),
    ("Last the round AJ. https://t.co/Fp4bcpB5tm", 'neg'),
    ("My fam and I were up till 5 am drinkin tequila and henny shots and my aunt made sum good ass margaritas too", 'neg'),
    ("me, full well knowing it could be dangerous: I WANT THEM TO MENTION ABBY'S BRAIN DAMAGE AGAIN", 'neg'),
    ("@Hullass1972 Got settled fight come on earlier than I thought so Sophie is watching", 'neg'),
    ("My guys career is over if he loses this", 'neg'),
    ("If your not a paying pig or retweeting there so be no reason your in my mentions losers  Either pay to lurk or get the fuck off my page ", 'neg'),
    ("He got slumped", 'neg'),
    ("I LOVE THESE TWO SO MUCH https://t.co/01hEwV0oGx", 'neg'),
    ("TEST  TWEET TO BE DELETED https://t.co/TVnomsUrX8 oo808304383", 'neg'),
    ("follow this (instagram) nadyagds and (twitter) nadyagdss", 'neg'),
    ("@SkySportsBoxing Oh my word!", 'neg'),
    ("y eso 'braids' jesu https://t.co/re7CqZLtt2", 'neg'),
    ("@honkposter 'We want D.va to be treated more seriously &amp; not just as a gamer gremlin!'*makes a police skin for D.va*'Wait no,'", 'neg'),
    ("they're both fighting like girls", 'neg'),
    ("*NEW #DATING TV SHOW* Do you have a #secret crush? Txt: 'SECRET' to 07710 168 268 #TVCasting #London #BankHoliday... https://t.co/ZaWK6gk6wM", 'neg'),
    ("Food and fashion enthusiasts alike will dig these sushi shoes https://t.co/2a2JmrB3CX https://t.co/CztI8IzZ84", 'neg'),
    ("AJ GETTING TERRORISED", 'neg'),
    ("God is real cause this the devil https://t.co/gJq1bcPC2v", 'neg'),
    ("@AyeDeeJaye bet! I just joined that group", 'neg'),
    ("@Enceladosaurus Mine didn't wear cologne much. But had a very specific sweet smell. He always had minty candies in... https://t.co/qeqY5HE1p0", 'neg'),
    ("ass, Man", 'neg'),
    ("Union of the races  https://t.co/1IsdlKxdlk", 'neg'),
    ("ESPN killed something else with its layoffs, its best hope to reach millennials: TrueHoop... https://t.co/NnyCunlfOI", 'neg'),
    ("In this episode, Mikenzie Hardman of Bitches n Brews joins the podcast as its first guest host. https://t.co/Y6W9qYZVqV  #craftbeer", 'neg'),
    ("We're #hiring! Read about our latest #job opening here: PACU Registered Nurse, RN - https://t.co/U2kDTjxgVw #Nursing #Denver, CO", 'neg'),
    ("Joshua looks fucked", 'neg'),
    ("first places re #choices that were made or not made depending on how one looks at it etc etc etc!! He hasn't even got the #courage to turn", 'neg'),
    ("It is not what happens to you but how you respond to what happens to you..", 'neg'),
    ("5 Reasons Why I Won't Vaccinate My Children - And You Shouldn't Either! https://t.co/8NRp2bSfxW", 'neg'),
    ("#NEWS Food and fashion enthusiasts alike will dig these sushi shoes https://t.co/N1aJaLfx13 https://t.co/eFEbYIDNwF", 'neg'),
    ("@AIarrapino Just don't break any...wind that is", 'neg'),
    ("i need vacuum iml", 'neg'),
    ("OK. but @chintskap said that no one new star came on the funeral, can you say about all of them same word ? https://t.co/B8v56aX3CF", 'neg'),
    ("@TheDouglasAllen 7 I think", 'neg'),
    ("@DUIthecrew Too white to be saying nigga", 'neg'),
    ("Pentagram (2016) by Surly Brewing Company found at The Tipsy Cow. Go get some!", 'neg'),
    ("Postmodern Jukebox One Take 2013 Mashup: Just Another Day at the Office https://t.co/uShzwc2VCK #staged https://t.co/5wgXvUKNs5", 'neg'),
    ("Me: I'm just going to quickly grab one orange Berkeley Bowl: plz take an hour to consider these 40 different orang...... https://t.co/F3evChk0it", 'neg'),
    ("but the sun's gonna rise, the sun's gonna rise like everyday", 'neg'),
    ("Now selling: Wooden guitar for music lovers, Collectible Guitar 3, Gift for boyfriend #music #art #woodworking... https://t.co/3iUzC9cO2Q", 'neg'),
    ("one person followed me and 2 people unfollowed me // automatically checked by https://t.co/u93IiiP0Hj", 'neg'),
    ("@theChosen__One well damn. ", 'neg'),
    ("I never knew Brad Kaaya's mom was Felicia from Friday lol", 'neg'),
    ("@A_Badassunicorn Pretty flowers", 'neg'),
    ("Architecture https://t.co/xF8oTHbWPO", 'neg'),
    ("@carnivac i wanna crop the 'BS: this is bait' for all my 'this is bait' reaction image needs even tho i would never use it", 'neg'),
    ("@TheChainsmokers FUCK YOU FOR BUTCHERING THE EMO NATIONAL ANTHEM", 'neg'),
    ("Local-Temp : 23.40 Local-Humidity: 47.60 Remote-Temp :  0.00 Remote-Humidity:  0.00 Time: 519944634 Counter: 0 Sensor: OK IAmArduino.", 'neg'),
    ("hopefully veggie burgers are an acquired taste", 'neg'),
    ("@NYRangers @BradySkjei Incredible defensive play first!", 'neg'),
    ("Me that's suppose to have been sleeping since..  @ALOFFAWY", 'neg'),
    ("Ready, Set, Go - Let's take a tour of a food manufacturing facility together... #DiscoverERP https://t.co/omYgqqGH7x", 'neg'),
    (".@NintendoAmerica forecasts 10 million #NintendoSwitch consoles this fiscal year https://t.co/IaSgl1NHUj https://t.co/zFXV6v5aYg", 'neg'),
    ("ReadersGazette: BLOG Spiritual Musings of Author Anthony Donnelly by Anthony Donnelly https://t.co/vONKzf9szy Author Anthony Donnelly Blog...", 'neg'),
    ("Treat yourself with love and respect, and you will attract people who show you love and respect", 'neg'),
    ("And welcome to you, who have come to Hidamari Apartments.", 'neg'),
    ("What are we suggesting? I'm late to the show. @CHANCEDXR @JeffHillyer @PATWEBBDXR @IamJohnRusnak #DeadXRadio", 'neg'),
    ("We look like 'The Culhanes' from 'Hee Haw'! https://t.co/S2wx5frHfO", 'neg'),
    ("Chow Tai Fook to Open Its Second Branded Boutique in the United States https://t.co/Ey151EWT0S", 'neg'),
    ("#Success #Affirmations for your #business https://t.co/WqPgeD4bTo #TheBabyBoomerMarker #successvideo #modavation https://t.co/Ow9R8EvaQy", 'neg'),
    ("GOLDEN Premium Tempered Glass Xiaomi Redmi 3 #lazada, product Buy: https://t.co/GILzfi2kSK https://t.co/nq3TQUEmYb", 'neg'),
    ("Felt good to reunite with my girl :)", 'neg'),
    ("@biglasmadrid this fight over Aj cant get out", 'neg'),
    ("The100 en Argentina  Dropship. https://t.co/1jbJElO1CS", 'neg'),
    ("im bored so talk shit x https://t.co/tzMU3CwHeP", 'neg'),
    ("#NewProfilePic bc queen!!  https://t.co/4XAlb1OFsY", 'neg'),
    ("@STINGLIKEA_BEY Why are you so bothered dhdbbddn still hurt about my hit that sticks like grit, which outsold your highest btw!", 'neg'),
    ("#News 'Stop beating Kupwara drums to hate Muslims: Farooq Abdullah' https://t.co/GM7x7fpCeB", 'neg'),
    ("BREAKING: North Koreas Chubby Dictator Threatens to Blow Up USS Carl Vinson https://t.co/VxwY5KWfF2 https://t.co/7yQg4E9MSA", 'neg'),
    ("AJ has never passed the 7th round.", 'neg'),
    ("Men who think they're hood vs. Actual hood men https://t.co/0FEeU6Oqlj", 'neg'),
    ("@NdukaUgwae @cchukudebelu Plus left the country in a state of extortion and celebration of impunity. Just a reminder.", 'neg'),
    ("Smokescreens in Islam: Confusing the Public about the Facts: https://t.co/ZsFCKJCQDx", 'neg'),
    ("Download this app for free...  https://t.co/Z1ULINXvum", 'neg'),
    ("When you give up trying.. that's when you know your done ", 'neg'),
    ("Weight Watchers Points Calculator &amp; Tracker https://t.co/SZX0fEffwn https://t.co/nxjbeZbYMw", 'neg'),
    ("Lol why can't people mind their own business? I'll find out who said it &amp; ill have something to say. Just wait.", 'neg'),
    ("what the fucketh is this poxy scuffle that everyones talking about? whats the score?", 'neg'),
    ("Y'all flexing", 'neg'),
    ("Food and fashion enthusiasts alike will dig these sushi shoes https://t.co/Jz30XQ1jbp https://t.co/fbmX9et8TT", 'neg'),
    ("couldn't do shit on my debian vps now because systemd timed out", 'neg'),
    ("Mature lady loves sucking yong guys hard cock https://t.co/8oBGGFVnPB", 'neg'),
    ("Eyyyy in gonna go to sleep for the first time this week without feeling like crap", 'neg'),
    ("https://t.co/fHk7GZO2tN  @Drake  new cover on my SoundCloud :)", 'neg'),
    ("I love you baby  https://t.co/eSiorfUDLO", 'neg'),
    ("Ppl be so mad when I don't want to hang out with them. Hang out for what? to waste my time ?", 'neg'),
    ("Tornado warning polygon includes Sallisaw and areas to the NE into the rest of Sequoyah County. #okwx @FOX23... https://t.co/R1X1KJrHCF", 'neg'),
    ("sometimes i wake up in the middle of the night and wonder why i write fic. how bizarre", 'neg'),
    ("Cuddles with bae are the best", 'neg'),
    ("Food and fashion enthusiasts alike will dig these sushi shoes https://t.co/MJOruiUrtr https://t.co/Rf6jMiQfR6", 'neg'),
    ("Police Charge Two Lawmakers From Slovak Far-Right Party With Extremism https://t.co/1PB3zZOUZT", 'neg'),
    ("Hey, .@ruleYork one or the other, which was more important. #FyreFestival   Gotta choose. Time is finite, you know... https://t.co/WkvOYXOdTs", 'neg'),
    (" RETWEET  IF  YOU  RAP   Follow @SoundCloudGain  17.4", 'neg'),
    ("@ElizabethLStein Sharing our window of opportunity @MolloyEdD https://t.co/rVfasSN4BH", 'neg'),
    ("We definitely do.... https://t.co/5z2FSDl2Ra", 'neg'),
    ("The weather is warming up, complete this week's #trailrunning #ParksChallenge while it's still shoulder season in o... https://t.co/6MNdHmPaG9", 'neg'),
    ("Just Announced: Montreal, Canada - May 20 at Birthday Bash @ R... https://t.co/DMY1MCVnhP", 'neg'),
    ("Man City out of Women's Champions League despite win in Lyon: Manchester City win their Women's Champions League...... https://t.co/M8ItTmr06I", 'neg'),
    ("Problem of being a heavy weight.. can't do 12 rounds ", 'neg'),
    ("'Ah, training time!' *hits one of those martial arts training dummies with wooden arms and immediately breaks every bone in my wrist*", 'neg'),
    ("Lil Yachty X Ilovemakonnen X Lil B Type Beat Instrumental 2 [FREE DOWNLOAD] https://t.co/khBpgoZD8X by JAKKOUTTHEBXX XXIV ...", 'neg'),
    ("Plus too much focus on Stark in the trailers at times. But Keaton as Vulture...fuck he looks awesome. #SpiderManHomecoming", 'neg'),
    ("I can't watch ", 'neg'),
    ("its was a dark and stormy night....St Louis", 'neg'),
    ("#miamiyellowtaxicabs FlipaClip app allows you to be an animator https://t.co/HcxaBhAzuY #miami #sobe https://t.co/PWJ0xVF3N0", 'neg'),
    ("Am being terrorized by huge wasp in the living room making loud buzzing noises against the paper light shade", 'neg'),
    ("Brian's Jr. prom. https://t.co/emOTFrsUf8", 'neg'),
    ("@Rambobiggs Linda ISIS Sarsour is a criminal", 'neg'),
    ("Happy 100 days of Trump", 'neg'),
    ("Check out my broadcast from my PlayStation 4! #PS4live (Destiny)  live at https://t.co/jjPXaC19la", 'neg'),
    ("Come on Dr Steelhammer @murraynisbet79 @eye_bee #joshuaklitschko", 'neg'),
    ("Nothing pisses me off more then someone fuckin up my nails or eyebrows ", 'neg'),
    ("Shit", 'neg'),
    ("@WilliamsRacing @karunchandhok @PaulDiResta Hi Rob,  what is your favourite race of the year and why!?", 'neg'),
    ("2019 Robert Shelton Team Loaded with 13 points in 63-56 win over Team Maryland. @TheHoopGroup #PittJamFest https://t.co/EbbQ1uSi4h", 'neg'),
    ("@NickyRR people who have never had insomnia have no idea !  Have you tried any bio oil on the your scars ?", 'neg'),
    ("@Adi_Frenchy It's Manhattan prices .. we can always catch the cart just because ", 'neg'),
    ("Jen Grope is now following me on Twitter! https://t.co/ZFCEkDFRaD Thanks!!!", 'neg'),
    ("Its over for joshua", 'neg'),
    ("@butlersbingo It's #FreebieFriday  We've got a massive Green &amp; Blacks Hamper to give away!  All you have to do is... https://t.co/9wHHifhUCZ", 'neg'),
    ("If fight goes beyond Round 6. #Klitschko will probs win!", 'neg'),
    ("#np Maroon 5 - Cold", 'neg'),
    ("Yamaha Pro Bobby Lane shares cold weather bass tips https://t.co/xEQuVrbaTz", 'neg'),
    ("Book one in Fargo, ND, and I'll be there!! https://t.co/CmOFxFJBnA", 'neg'),
    ("Hands up Joshua", 'neg'),
    ("You want to buy a car or house or sell any of them, but you dont have the market. DM us, we will connect you to ur market @Gidi_Traffic", 'neg'),
    ("@AricSharpknight shut it atleast its better than the last terrain &gt;:(", 'neg'),
    ("The big boy is deffo to big for this ", 'neg'),
    ("Fair play to both fighters here!", 'neg'),
    ("I have no extra thoughts today, thank you", 'neg'),
    ("HAM-A-HADDIE is an old Scots word for a highly unlikely story or situation.", 'neg'),
    ("One frustrating thing about how fast media formats change is it almost guarantees some entertainment related strike every couple of years.", 'neg'),
    ("Saints Row 2 (Sony PlayStation 3) | Complete | Free Shipping!! https://t.co/DUfA1F6r6J https://t.co/l53FD8sB1d", 'neg'),
    ("@MissKerryDiva I doubt it honestly", 'neg'),
    ("Getting some Mexican food (@ Los Comales Taqueria) on #Yelp https://t.co/CKPjtxGaDF", 'neg'),
    ("Small town efforts! National refugee debate gets a small-town stage in Montana https://t.co/rCkwWrETam via @seattletimes #MSW521", 'neg'),
    ("i think i'm gonna delete my twitter i'm just really not feeling this anymore", 'neg'),
    ("Your tweet has not been delivered. Please try later. https://t.co/ODhegpx9VA", 'neg'),
    ("I added a video to a @YouTube playlist https://t.co/52M4b8RdaA FOREIGN KIDS AT COLLEGE / Q&amp;A", 'neg'),
    ("Nothing is impossible, the word itself says, Im possible! Audrey Hepburn", 'neg'),
    ("@ReFridgeinator @qyfil I am too, Im sorry. I deleted the goofy pic because u dont like drogs i dont think he's a dog, but he is still creepy", 'neg'),
    ("@msellithorpe You might enjoy #PumpkinFarmer: https://t.co/M20DCi71jH #amreading #IARTG #goodreads #KindleDeals #retweet", 'neg'),
    ("@abbyburnistonxo Girl you'd be shocked", 'neg'),
    ("Let's go Wladamirrr", 'neg'),
    ("Joel's Sign May Be In Your Front Yard...Now It's Time To Put Him In Office! VOTE For Joel Munguia City Commissioner... https://t.co/VSZVTbQTAj", 'neg'),
    ("They put me at  place , they put me at place , so show me you different girl, put me at  place ! Show me a new light baby", 'neg'),
    ("oh yea RUB IT ZUCKAS RUB IT BIG BOY! https://t.co/EHruoAl4sn", 'neg'),
    ("@Fatman003 Make I know if you don sabi am", 'neg'),
    ("@khaawlla_ i love you too ya a7la shy !", 'neg'),
    ("@SLS_Football Great Job Merc !!  Keep the pace and always look forward Big Man", 'neg'),
    ("Turkey just banned Wikipedia, labeling it a 'national security threat' https://t.co/wnu7q0wOHR", 'neg'),
    ("Drinking a Pinsetter by @RealAleBrewing at @pouringglory  https://t.co/2buGQBmr3C #photo", 'neg'),
    ("klitschko caught him so clean with that right omg", 'neg'),
    ("@morningmoneyben @nytimes Haaha no we stopped reading that filthy rag which has been out to destroy Trump since day one lying piece of crap", 'neg'),
    ("The Magic in Sleight Makes Up for an Otherwise Familiar Tale https://t.co/SbrAmoy6hA https://t.co/3fzBbfXdxr", 'neg'),
    ("1 more guys", 'neg'),
    ("@pistons15 May you message me please i have some important message to tell you", 'neg'),
    ("The Fyre Festival Was a Luxury Nightmare https://t.co/TTu7fpfpny via @jiatolentino", 'neg'),
    ("Joshua is done right about round 7 or 8. Really dont see any kind of comeback. #JoshuaKlitschko", 'neg'),
    ("does my new finger tattoo count as fanart @iceddarkroast #arubiancompf https://t.co/8WLzR3iLYV", 'neg'),
    ("Real live. https://t.co/9GvV1qJpJc", 'neg'),
    ("@Meukowian I don't like the country music", 'neg'),
    ("#8283 #Save #Buy #deals How to Read Music Notes for the Adult Beginner https://t.co/fN4vhgSAaE https://t.co/pkjDTztD19", 'neg'),
    ("I added a video to a @YouTube playlist https://t.co/y0hET68Sxk 'Balloons' - Five Nights at Freddy's 3 Song | by MandoPony", 'neg'),
    ("@realDonaldTrump @LouDobbs Re: your 100 day 'contract' ... for the record, with notes, like I said the most ineffec... https://t.co/q363XnGxTi", 'neg'),
    ("I miss going to bed with absolutly nothing on my mind", 'neg'),
    ("Burnley ease relegation fears by beating Palace for elusive away win https://t.co/76W9yl6HpU https://t.co/0nRDAoij8K", 'neg'),
    ("Do souls look like pickles", 'neg'),
    ("Joshua canny take a fuckin punch been fighting nobodies for years", 'neg'),
    ("Tryna get my karma up ", 'neg'),
    ("Very little pain, however. Which I'm more than grateful is the case as it's supposed to be utterly agonising @_@'", 'neg'),
    ("..Imagine if Klitschko was 10 years younger? Lmfao..", 'neg'),
    ("Joshua is struggling", 'neg'),
    ("Get Your limited edition presidential clothing   #inauguration#trumpinauguration #trump #obama #presideration  https://t.co/AcsgFEBJLM", 'neg'),
    ("How to Revive Your Dwindling Organic Facebook Reach via @KayaIsmail  #social #cx https://t.co/ddJPTYWU2A https://t.co/PZAaZXiQTQ", 'neg'),
    ("All the feels for @AIANational day 3 keynote @amyjccuddy and the science of being powerful and present #A17con... https://t.co/TsqV2bPjBL", 'neg'),
    ("It's National Week of the Ocean! Sharing Fun Facts about Sea Life! Fun Fact #6: A 20 foot long Electric Eel can... https://t.co/OtcRWr6MDq", 'neg'),
    ("I was previously married to a narcissist so I know the script well. Always on eggshells of course we didn't have mi... https://t.co/bhpFwMNf07", 'neg'),
    ("Aquarius wins for best Air sign though ", 'neg'),
    ("Someone told me stay away from things that are yours #TeamNiall", 'neg'),
    ("Advertise Your Website to Millions of People With Our City Pennysaver.  FREE MEMBERS Earn Instant CASH Commissions!... https://t.co/moUT7GKjqM", 'neg'),
    ("See the complete Carolina Herrera Fall 2017 Ready-to-Wear collection. https://t.co/8RjmKH68v1", 'neg'),
    ("Here's #2b from #nierautomata for #cutiesaturday!  #NieR #nier_automata #art #videogames #fanart #artstyle #drawing... https://t.co/kbwqvWwL2T", 'neg'),
    ("Jones New York Women's Sleeveless jacquard Print Dress SZ 4 maxi summer Blue   via eBay https://t.co/usNcxSA6iT https://t.co/FiDZH4zxnH", 'neg'),
    ("Slips back on the crime bus on a time travel trip to Weird West Adams, where pretty places have ugly secrets.... https://t.co/zCy5z9amkZ", 'neg'),
    ("You don't want to make Batman angry! Call me. https://t.co/abydQ4svPL", 'neg'),
    ("Ajs chin being tested for the first time", 'neg'),
    ("Genuine authenticity can't help but lead to love.", 'neg'),
    ("THIS DRAFT SUCKS FIRE JERRY REESE", 'neg'),
    ("After a tumultuous start, Trump hopes for a smoother agenda on jobs and taxes - Washington Post https://t.co/3z3uewreZE", 'neg'),
    ("WRITING THE COZY MYSTERY is a recipe for success. #iBooks https://t.co/vM7GYGgXcD", 'neg'),
    ("rivers in the desert is the best P5 song and if you disagree you're fucking gay https://t.co/iZW2pm0iB3", 'neg'),
    ("Why the polls are wrong about Trump. Again. https://t.co/IOkY0ejaJA  By a Democrat pollster", 'neg'),
    ("@JohnnieGuilbert  commented on my cover of Someone So Damn Amazing !! #someonesodamnamazing #lostep... https://t.co/TaqpZTWsO1", 'neg'),
    ("Better to fight for something than live for nothing.- General Patton #quote", 'neg'),
    ("Good afternoon everyone, hope you are all doing well.", 'neg'),
    ("@tavia_marez that's what you think...", 'neg'),
    ("Am I in love with you or am i in love with the feeling?", 'neg'),
    ("@bubseunha dude that test was kinda easy even though I didn't finish my leq", 'neg'),
    ("@jackdre02 He is!! Just because he didn't score Vs certain teams doesn't just suddenly change that fact!", 'neg'),
    ("@jUicYH0e Thanks buns-mama!! I really want to be eating more veg because lately I've been relying on too many substitutes! ", 'neg'),
    ("@Patricia_Traina 5-3 Rangers. 12:48 left in 3rd period", 'neg'),
    ("Wait wait wait, brad kaaya's mom is Felicia from Friday?!?!?", 'neg'),
    ("@followondering Seriale: pretty little liars, stranger things, girl meets world", 'neg'),
    ("@chunkymark we must vote tactically to stop the tories visit https://t.co/DJK1QQnWsA", 'neg'),
    ("How To Write a Documentation For You Web Development Project https://t.co/LZXpj5U9WQ #webdeveloper #youtuber #programming", 'neg'),
    ("Photos: Saunders vs. White Plains softball https://t.co/AF6pRQc2dm https://t.co/RjCn6YtMbt", 'neg'),
    ("Just posted a photo https://t.co/ef5uk5haVH", 'neg'),
    ("Joshua is burnt out #JoshuaKlitchsko", 'neg'),
    ("#Amazon #LightningDeal Beautiful Rose Gold insulated tumblers perfect 4 hot/cold drinks! All 3 sizes! #sale #deal... https://t.co/5OBz4vbhw4", 'neg'),
    ("i'm in love with downtown and everything it has to offer https://t.co/fHxLrTSkXN", 'neg'),
    ("Picture this! Cubs dug out &amp; killed. Two terrier men grinning at the camera as they hang the still live lactating vixen by her ears.", 'neg'),
    ("@SLM9461 All together", 'neg'),
    ("Big engineering to protect #Rotterdam and South Holland #Maeslantkering   https://t.co/yF9okxSnnL", 'neg'),
    ("@XyzalAllergy Tried it. Doesn't work for me.", 'neg'),
    ("@misterjoethethi @YoshinoAE Well its hard to find somethong that 100% matches..", 'neg'),
    ("@Roark86 It's also not forced integration if one property owner sells or rents their property to someone else. To prevent that is force.", 'neg'),
    ("The crowd at Wembley is clearly AJ's support tonight!!!!! Come on AJ hold on!!! Clevs has gone now beers everywhere AGAIN ", 'neg'),
    ("Not having an emotional outlet is taking a toll on my MH, but there is no help available", 'neg'),
    ("OFFICIAL Microsoft XBOX 360 250GB Slim Hard Drive OEM Original Genuine Authentic https://t.co/zOjeXjdubx https://t.co/C0dXHO7EaY", 'neg'),
    ("We need to get rid of carbon in the atmosphere, not just reduce emissions https://t.co/UCIFX5G50V #itstimetochange #climatechange @ZEROCO2_*", 'neg'),
    ("As College Deadlines Near, Families Wonder What They Can Pay https://t.co/k4Wk83gKsY", 'neg'),
    ("@Sadiesgathering A tropical beach w/ a fruity alcoholic beverage. But no, I'm at a goddamn march in 2017 STILL tryi... https://t.co/3gdCfoKLU2", 'neg'),
    ("@rabeisqueen It might not be as fancy as the other words but it's definetely fkn true ", 'neg'),
    ("AJ is dead on his legs", 'neg'),
    ("I'm another year older, wiser and happier   #April #30 ", 'neg'),
    ("Just wait and see.", 'neg'),
    ("Favorite babe https://t.co/gPtOkWMFTm", 'neg'),
    ("@SophieHartxxx you are a spectacular vision of majestic beauty in all your sensual pictures you are incredibly beautiful.", 'neg'),
    ("What a hit from Klitschko", 'neg'),
    ("@bbcvirgin1 So am I", 'neg'),
    ("Bro its way To hott omg", 'neg'),
    ("Backyard Becky. https://t.co/x0iq2Kpelb", 'neg'),
    ("@ShittyVirus what", 'neg'),
    ("VIDEO INSIDE: Charly Black Is The First Dancehall Artist To Perform In Paraguay https://t.co/FryoHUN7Kl", 'neg'),
    ("Bcoz ppl come 2 rely on d fact dat wht u r saying is not simply d movement of yo mouth, but rather a Plan of Action dat u plan 2 embark upon", 'neg'),
    ("They must gerarahere for real man shi. https://t.co/zi36n6iJtt", 'neg'),
    ("If you're not watching this right now, you should be. Dragged myself out of the house to find wifi. Join us! https://t.co/7w62HVgtzg", 'neg'),
    ("Now share content in your own language https://t.co/9TPPWFOGmM", 'neg'),
    ("Happy Birthday Michelle Pfeiffer! https://t.co/Ri7gnsQ3JB", 'neg'),
    ("@BluEyezMess Obama should get a stock market crash *", 'neg'),
    ("#Riverdale 'Kids in America' - MAJOR 90S THROWBACK. This song always makes me think of the #Clueless opening.", 'neg'),
    ("@gduffett @GodDoesnt @nytimes If you find me 3 science models you approve of, I'll pull out both the intra and inter model uncertainty. 1/2", 'neg'),
    ("I just entered the @noblegg @arozzichairs #giveaway you can too! https://t.co/LAbYRuJesx #StayNoble", 'neg'),
    ("atreveteydejatesorprender@hotmail.com 3206962816 y 3156304823 (+57) INTERVIEW: FOUNDER OF THE LUCIFERINO TEMPLE https://t.co/ggPHc24bnT", 'neg'),
    ("@sebtsb Omg yess please", 'neg'),
    ("I've been carnivorous my whole life and decided to stop cold turkey(lol) to be pescatarian. Damn this is hard.", 'neg'),
    ("@mattyglesias During @POTUS' first #100Days he has fulfilled promise after promise &amp; we're already seeing results.... https://t.co/EW0EakWdTr", 'neg'),
    ("YOUNG FELLA YOU JUST GOT DROPPED BY KLITSCHKO", 'neg'),
    ("@btstaton Today, I attend the Eulogy Seminar taught by this man of God and it was phenomenal!!! God bless you Pastor Billy.", 'neg'),
    ("Now playing: 'When You're Gone' by 'Kungs feat. Tillie'", 'neg'),
    ("My body feels so weak ", 'neg'),
    ("@Jose_Arrogantio third date huh...good to know ", 'neg'),
    ("@naretevduorp @shawrls @realDonaldTrump @LouDobbs Roger Aisles and Bill O'Reilly say they're misunderstood too.", 'neg'),
    (": outclassed but roguish: stepped, but not untestable", 'neg'),
    ("@adriantoomey @jamieweeks70 Oh. Hello. This still going?", 'neg'),
    ("@KarleighMcbride Me? Yes", 'neg'),
    ("after i told my mom a guy threw me into the road and i just laid like a starfish in the middle of the road https://t.co/U7wbhpjKUE", 'neg'),
    ("Ima examine words bullys usebare with me my next post will be up about a word in a sec", 'neg'),
    ("Disappointed in Anthony Joshua", 'neg'),
    ("Exactly https://t.co/mXvoGPaxEd", 'neg'),
    ("@Jizzeemoto Fuck no!", 'neg'),
    ("@emsccscotland Pretty nice :)", 'neg'),
    ("Issss BEAUTIFUL https://t.co/fw7tCNBhlC", 'neg'),
    ("@MrAzzaDnB I know omg", 'neg'),
    ("I liked a @YouTube video https://t.co/RSGNvn52fh Primitive Technology: Termite clay kiln &amp; pottery", 'neg'),
    ("God only gave us 1 book. In that book is our chapters of life. We write our chapters in our life .. no else does. Live life how you want to", 'neg'),
    ("Lmao this is literally my cat https://t.co/Z07612EAD5", 'neg'),
    ("Antique Early 20thC Japanese Cloisonne Bird &amp; Flowers Enamel Charger Plate, NR https://t.co/OBxVAgRpUr https://t.co/v2KLbKM4Vu", 'neg'),
    ("The latest The FF Fortune Teller's Almanac! https://t.co/CawcJrGPLP #fantasyfootball #nfldraft", 'neg'),
    ("John Lennon - Mind Games: https://t.co/UzkULHd9gF", 'neg'),
    ("So excited for tonight!!!", 'neg'),
    ("i'm back down to 2k can someone give me ffs", 'neg'),
    ("@WhiskeyJam When are there going to be outdoors ones again?", 'neg'),
    ("Congrats @kaaya323 on getting drafted to the league! Time to go to work! #NFLDraft  #TheU #GoCanes", 'neg'),
    ("Celebrating a commercial when the product doesn't even cater to ur hair lmaooooo fuckin bozos", 'neg'),
    ("@Steel_Curtain4 Surprised they didnt draft an ILB", 'neg'),
    ("@PLLTVSeries Really? Aria deserves much better", 'neg'),
    ("Titmouse Bird Print  Gray and White https://t.co/LCy718RKuv #birds #wildlife #fineart https://t.co/Gn2fHzzQdI", 'neg'),
    ("'True love is rare, and it'spthe only thing that gives life real geaning.'", 'neg'),
    ("@SeanSullivanNBA @acommoncreeper 'Player comparison: Willie Young, Chicago Bears Neither Young nor Watt is eye-pop... https://t.co/ZZz4JxNGzc", 'neg'),
    ("El Jardin's food goes crazy", 'neg'),
    ("NASA for High-Speed Space Internet #GLvMI https://t.co/ii4tffwCnw", 'neg'),
    (" Butterfly SAPPHIRE  giveaway with @skinupgg and @TheGrefgYT right now!  Check  https://t.co/UX6Ovk9ga1", 'neg'),
    ("Another Richt qb to help them lose in the first round https://t.co/E1cncBBZcZ", 'neg'),
    ("@RSmithNFL @NYGDaily @PFF Plays like Josh Sitton. Similar profile/skill set.", 'neg'),
    ("one person followed me and one person unfollowed me // automatically checked by https://t.co/Jn3JcFaTnB", 'neg'),
    ("@POTUS KKKIIIMMMGGG RRRAAAMMMAAA 9 PERFORMEEEDDD DUTTTIII VAROUS TTTIIILLL MORE 4000 MATIOMAL PROJECKSSS https://t.co/ieTi8LGQfX  REFERRED", 'neg')
]

if __name__ == "__main__":
    # cl = NaiveBayesClassifier(train)
    print("Starting train to machine...")
    with open("train.json", 'r') as fp:
        cl = NaiveBayesClassifier(fp, format="json")
    print("Train Dataset ... Completed")

    # Classify some text
    # print(cl.classify("faithful tracer porn #feminisim"))  # "pos"
    # print(cl.classify("I don't like their pizza."))   # "neg"

    # Compute accuracy
    print("Starting test to machine...")
    print("Accuracy: {0}".format(cl.accuracy(test)))

    # Show 5 most informative features
    cl.show_informative_features(10)